### PR TITLE
bugfix: keadm reset edge failed to remove containers

### LINKED ISSUE #6535: keadm reset edge failed with runtime error: invalid memory address or nil pointer dereference
**What happened**:
when use keadm version v1.22.0, keadm reset edge always failed,

Image

**What you expected to happen**:
keadm reset edge success and edge containers were clean up

**How to reproduce it (as minimally and precisely as possible)**:
use keadm version v1.22.0, and execute `keadm reset edge`.

**Anything else we need to know?**:
`containerRuntime.Connect` need to be called before use.

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by will4j**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6535

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by will4j** [comment]
> the fix itself looks good to address the issue.
> 
> but i think gemini makes sense here, it would be really nice to have this under generic implementation agnostic from platform. this is also good for maintenance.



> the fix itself looks good to address the issue.
> 
> but i think gemini makes sense here, it would be really nice to have this under generic implementation agnostic from platform. this is also good for maintenance.

I just want to fix the issue, but as gemini reviewed, use util.RemoveContainers to reduce duplicated code and it do good for maintenance, so i did a little bit refactoring.

File: keadm/cmd/keadm/app/cmd/util/reset.go [hunk 1]
```diff
@@ -43,6 +43,9 @@ func RemoveContainers(criSocketPath string) error {
 	}
 
 	containerRuntime := utilruntime.NewContainerRuntime(criSocketPath)
+	if err := containerRuntime.Connect(); err != nil {
+		return err
+	}
```
Comment (will4j) [inline keadm/cmd/keadm/app/cmd/util/reset.go:48]: I noticed that in latest k8s repo, a `Close` method is added to `ContainerRuntime` interface, so if upgrade dependencies in the following version, it may need to add `defer containerRuntime.Close()` as well. Which indicates that the impl now has potential resources leak problem, and it is far beyond this pull request.

Comment (will4j) [reply keadm/cmd/keadm/app/cmd/util/reset.go:48]: see https://github.com/kubernetes/kubernetes/pull/133893

**Comment by luomengY** [comment]
Resolve the e2e test error first.

File: keadm/cmd/keadm/app/cmd/util/reset.go (hunk 1 above)
Comment (Shelley-BaoYue) [reply keadm/cmd/keadm/app/cmd/util/reset.go:48]: Thanks for you remind. : )

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve

**Review by Shelley-BaoYue — COMMENTED** [review]
Hi, @will4j Could you please cherry-pick this PR to previous releases(maybe release 1.19-1.22)?  FYI: https://kubeedge.io/docs/developer/cherry_pick
