### PR TITLE
fix using same namespace while syncPodStatus

### LINKED ISSUE #1700: Pod status can not be updated because of namespaces in message is wrong
**What happened**:
I depoyed some pods which have different namespace on edgenode. At a unknown moment, I found my pods status gotten by "kubectl get -oyaml" are aways unready. Logs shows that message sent from edgenode is wrong in namespace.

**What you expected to happen**:
Pod status update normally

**How to reproduce it (as minimally and precisely as possible)**:
The bug may reproduce by restarting cloudcore some times, or restarting edgecore. I only remember doing restarting before I found the bug.

**Anything else we need to know?**:

- cloudcore log
image
- edgecore log
image

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  v1.3.0

### PR DESCRIPTION
**Pull request by GsssC**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
fix merging different namespace podstatus  into same ns message while syncPodStatus
**Which issue(s) this PR fixes**:

Fixes #1700

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by fisherxu** [comment]
Will review today, and could you please rebase the master branch to fix the ci first?

**Comment by GsssC** [comment]
> Will review today, and could you please rebase the master branch to fix the ci first?

done

File: edge/pkg/metamanager/process.go [hunk 1]
```diff
@@ -549,12 +545,17 @@ func (m *metaManager) syncPodStatus() {
 			klog.Errorf("unmarshal podstatus[%s] failed, content[%s]: %v", v.Key, v.Value, err)
 			continue
 		}
-		content = append(content, podStatus)
+		if _, ok := contents[namespaceParsed]; !ok {
+			contents[namespaceParsed] = []interface{}{podStatus}
```
Comment (fisherxu) [inline edge/pkg/metamanager/process.go:549]: Do we need this line here? Why not append directly.

Comment (GsssC) [reply edge/pkg/metamanager/process.go]: done : )
you r rigint, I thought the argument couldn't be nil.

File: edge/pkg/metamanager/process.go [hunk 2]
```diff
@@ -549,12 +545,13 @@ func (m *metaManager) syncPodStatus() {
 			klog.Errorf("unmarshal podstatus[%s] failed, content[%s]: %v", v.Key, v.Value, err)
 			continue
 		}
-		content = append(content, podStatus)
+		contents[namespaceParsed] = append(contents[namespaceParsed], podStatus)
+	}
+	for namespace, content := range contents {
+		msg := model.NewMessage("").BuildRouter(MetaManagerModuleName, GroupResource, namespace+constants.ResourceSep+model.ResourceTypePodStatus, model.UpdateOperation).FillBody(content)
+		sendToCloud(msg)
+		klog.Infof("sync pod status successful for namespaces %s, %s", namespace, msgDebugInfo(msg))
```
Comment (fisherxu) [inline edge/pkg/metamanager/process.go:553]: We can set the log level here to avoid to many logs, `klog.V(3).Infof`.
Ref: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L578

File: edge/pkg/metamanager/process.go [hunk 3]
```diff
@@ -549,12 +545,14 @@ func (m *metaManager) syncPodStatus() {
...
-
-	msg := model.NewMessage("").BuildRouter(MetaManagerModuleName, GroupResource, namespace+constants.ResourceSep+model.ResourceTypePodStatus, model.UpdateOperation).FillBody(content)
-	sendToCloud(msg)
-	klog.Infof("sync pod status successful, %s", msgDebugInfo(msg))
+	for namespace, content := range contents {
+		msg := model.NewMessage("").BuildRouter(MetaManagerModuleName, GroupResource, namespace+constants.ResourceSep+model.ResourceTypePodStatus, model.UpdateOperation).FillBody(content)
+		sendToCloud(msg)
+		klog.V(3).Infof("sync pod status successfully for namespaces %s, %s", namespace, msgDebugInfo(msg))
+	}
+	klog.Infof("successfully sync pod status in edge-store to cloud")
```
Comment (fisherxu) [inline edge/pkg/metamanager/process.go:555]: Default logs should focus on the error log, this successfully log will be printed out periodly, I think it's useless and can remove it, WDYT?

Comment (GsssC) [reply edge/pkg/metamanager/process.go:555]: Yes, it sounds all reasonable

> Default logs should focus on the error log, this successfully log will be printed out periodly, I think it's useless and can remove it, WDYT?

Yes, it sounds all reasonable
