### PR TITLE
Fix the edge node takes too long time to get ready when reconnect

### LINKED ISSUE #1545: edge node does takes very long to become Ready in kubernetes if edgecore crashes and is restarted
**What happened**:

I launched cloudcore on the cloud, then I launched manually edgecore on the edge. Everything works fine and the node becomes 'Ready' quite fast (10-15 seconds at most).

Now if I kill edgecore, wait for the node to become 'NotReady', and then launch edgecore manually, the node will take around 4 minutes to become available again. If I stop cloudcore and then restart both cloudcore and edgecore in that order the node on the edge will become Ready in 10-15 seconds.

**What you expected to happen**:
I would expect the node to become 'Ready' within 10-15 seconds which is what it takes on a fresh cloudcore/edgecore launch

**How to reproduce it (as minimally and precisely as possible)**:
See the answer to the first question

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

cloudcore:
KubeEdge v1.2.0-beta.0.157+adcdceaf9bafbf-dirty
edgecore: 
KubeEdge v1.2.0-dirty

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): Raspberry Pi 4 4GB

Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1750.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid

- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

- Kernel (e.g. `uname -a`):
Linux kube-master.cassiopeia.local 5.3.0-1018-raspi2 #20-Ubuntu SMP Mon Feb 3 19:45:46 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

- Go version (e.g. `go version`): 
1.13
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
KubeEdge v1.2.0-dirty

- Hardware configuration (e.g. `lscpu`): Raspberry Pi 3

Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     1200.0000
CPU min MHz:                     600.0000
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid

- OS (e.g. `cat /etc/os-release`):
Yocto based custom distribution
- Kernel (e.g. `uname -a`):
Linux kube-edge.cassiopeia.local 4.19.105-v8 #1 SMP PREEMPT Wed Mar 11 13:44:07 UTC 2020 aarch64 GNU/Linux

- Go version (e.g. `go version`): 
1.13
- Others:

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:
Use one goroutine for one edgenode, fix edge node takes too long time to get ready when reconnect.

**Which issue(s) this PR fixes**:

Fixes #1545 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix the edge node takes too long time to get ready when reconnect
```

### CODE REVIEW

**Comment by fisherxu** [comment]
Now the CI has passed, ptal :) @kevin-wangzefeng @GsssC @kadisi @ls889

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 1]
```diff
@@ -250,10 +255,9 @@ func (mh *MessageHandle) ServeConn(hi hubio.CloudHubIO, info *model.HubInfo) {
```
Comment (GsssC) [inline cloud/pkg/cloudhub/handler/messagehandler.go:255]: Because  not every time node connection establishment will call `ServeConn`, how about changing it to `ServeNode` , using ` mh.nodeConns.get(nodeName)` in this func instead of the parameter of `hi hubio.CloudHubIO` . Then the task of `OnRegister(better change to OnConnected)` is to change the dead broken connection to the new active one.

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 2]
```diff
@@ -145,26 +145,31 @@ func (mh *MessageHandle) OnRegister(connection conn.Connection) {
 	}
 
 	io := &hubio.JSONIO{Connection: connection}
+
+	if _, ok := mh.nodeRegistered.Load(nodeID); ok {
+		mh.nodeConns.Store(nodeID, io)
```
Comment (GsssC) [inline cloud/pkg/cloudhub/handler/messagehandler.go:150]: Will old broken io be closed automatically?

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 3]
```diff
@@ -250,10 +255,9 @@ func (mh *MessageHandle) ServeConn(hi hubio.CloudHubIO, info *model.HubInfo) {
...
 	klog.Infof("edge node %s for project %s connected", info.NodeID, info.ProjectID)
 	exitServe := make(chan ExitCode, 3)
-	stopSendMsg := make(chan struct{})
 
 	for _, handle := range mh.Handlers {
-		go handle(hi, info, exitServe, stopSendMsg)
+		go handle(info, exitServe)
 	}
 
 	code := <-exitServe
```
Comment (GsssC) [inline cloud/pkg/cloudhub/handler/messagehandler.go:263]: ExitCode there seem only could be `nodeStop`, which is generated by `kubectl delete node`

**Comment by GsssC** [comment]
The old source code of MessageHandler is too confusing. Especially the lifecycle of Message consumers such as`ListMessageWriteLoop` is deeply coupled with connection establishment.We would better decouple them.

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 4]
```diff
@@ -57,14 +56,15 @@ type MessageHandle struct {
 	Nodes             sync.Map
```
[the remark this answers is not in the document]
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:56]: Nodes here indicates how many edgenodes inflight(Already connected).

File: cloud/pkg/cloudhub/handler/messagehandler.go (hunk 3 above)
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:263]: Yes, now if the node haven't been deleted, we will not quit the goutines

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 5]
```diff
@@ -145,26 +145,31 @@ func (mh *MessageHandle) OnRegister(connection conn.Connection) {
 	}
```
[the remark this answers is not in the document]
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:145]: This make sense to me

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 6]
```diff
@@ -57,14 +56,15 @@ type MessageHandle struct {
 	Nodes             sync.Map
 	nodeConns         sync.Map
 	nodeLocks         sync.Map
+	nodeRegistered    sync.Map
```
[the remark this answers is not in the document]
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:59]: See the reply in first comment :)

File: cloud/pkg/cloudhub/handler/messagehandler.go (hunk 2 above)
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:150]: Done, already added the close func here.

File: cloud/pkg/cloudhub/handler/messagehandler.go (hunk 1 above)
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:256]: make sense, done

File: cloud/pkg/cloudhub/handler/messagehandler.go (hunk 2 above)
Comment (GsssC) [reply cloud/pkg/cloudhub/handler/messagehandler.go:151]: !!The stored value of nodeRegisted is not a connection, according to `mh.nodeRegistered.Store(info.NodeID, true)`

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 7]
```diff
@@ -275,26 +287,32 @@ func (mh *MessageHandle) RegisterNode(hi hubio.CloudHubIO, info *model.HubInfo)
...
 // UnregisterNode unregister node in cloudhub
-func (mh *MessageHandle) UnregisterNode(hi hubio.CloudHubIO, info *model.HubInfo, code ExitCode) {
+func (mh *MessageHandle) UnregisterNode(info *model.HubInfo, code ExitCode) {
+	if hi, err := mh.getNodeConnection(info.NodeID); err == nil {
+		notifyEventQueueError(hi, code, info.NodeID)
+		err = hi.Close()
+	}
+
 	mh.nodeLocks.Delete(info.NodeID)
 	mh.nodeConns.Delete(info.NodeID)
```
Comment (GsssC) [inline cloud/pkg/cloudhub/handler/messagehandler.go:304]: conn here also need to be closed?

File: cloud/pkg/cloudhub/handler/messagehandler.go [hunk 8]
```diff
@@ -145,26 +145,35 @@ func (mh *MessageHandle) OnRegister(connection conn.Connection) {
...
 			keepaliveTicker.Reset(time.Duration(mh.KeepaliveInterval) * time.Second)
 		case <-keepaliveTicker.C:
-			klog.Warningf("Timeout to receive heart beat from edge node %s for project %s",
-				info.NodeID, info.ProjectID)
-			stopServe <- nodeDisconnect
-			close(stopSendMsg)
-			return
+			if _, ok := mh.nodeConns.Load(info.NodeID); ok {
+				klog.Warningf("Timeout to receive heart beat from edge node %s for project %s", info.NodeID, info.ProjectID)
+				mh.nodeConns.Delete(info.NodeID)
```
Comment (GsssC) [inline cloud/pkg/cloudhub/handler/messagehandler.go:175]: conn here may also need to be closed?

File: cloud/pkg/cloudhub/handler/messagehandler.go (hunk 7 above)
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:304]: Will be closed in L300 here

File: cloud/pkg/cloudhub/handler/messagehandler.go (hunk 8 above)
Comment (fisherxu) [reply cloud/pkg/cloudhub/handler/messagehandler.go:176]: Done :)

**Comment by GsssC** [comment]
lgtm，but I think we still need to start a discussion about the code architecture, the lifecycle of msgQueue , msg consumers , connection and so on. I will think more and submit a issue next week. 

: )

**Comment by fisherxu** [comment]
> lgtm，but I think we still need to start a discussion about the code architecture, the lifecycle of msgQueue , msg consumers , connection and so on. I will think more and submit a issue next week.
: )

Yes, as the short-term workaround, this PR can fix some issues.
