### PR TITLE
kubeedge version support

### LINKED ISSUE #650: edgecontroller and edge_core need support show current detail version
**What would you like to be added**:
edgecontroller and edge_core and other kubeedge binary need support print current detail version, such as 
```
Version: 2e77d11
Revision: 2e77d11631c0067e3366242a7fc9a6f5700bebc6
Goversion: go1.11
Branch: version
```
**Why is this needed**:

we can use this detail version info to debug or track some question.

and our bug report will more detailed。
such as
```

**Environment**:
- KubeEdge version:
- kubeedge Revision:
- GoVersion:
- Branch: 
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:


```

### PR DESCRIPTION
**Pull request by kadisi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind feature

**What this PR does / why we need it**:

cloudcore, edgecore, edgesite, keadm upport show current detail version.

this is an example about keadm:
```
# keadm version

version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-286+4b36cde6dbed8f", GitCommit:"4b36cde6dbed8fbd4ac9b0314e20102027e722ed", GitTreeState:"clean", BuildDate:"2019-08-21T08:03:59Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}

# keadm version -o short
v1.0.0-286+4b36cde6dbed8f

# keadm version -o json
{
  "major": "1",
  "minor": "0+",
  "gitVersion": "v1.0.0-286+4b36cde6dbed8f",
  "gitCommit": "4b36cde6dbed8fbd4ac9b0314e20102027e722ed",
  "gitTreeState": "clean",
  "buildDate": "2019-08-21T08:03:59Z",
  "goVersion": "go1.12.7",
  "compiler": "gc",
  "platform": "linux/amd64"
}

#keadm version -o yaml
major: "1"
minor: 0+
gitversion: v1.0.0-286+4b36cde6dbed8f
gitcommit: 4b36cde6dbed8fbd4ac9b0314e20102027e722ed
gittreestate: clean
builddate: "2019-08-21T08:03:59Z"
goversion: go1.12.7
compiler: gc
platform: linux/amd64


```

it works like kubeadm.

**Which issue(s) this PR fixes**:

Fixes #650 

**Special notes for your reviewer**:

cc @fisherxu @sids-b @rohitsardesai83 @subpathdev @kevin-wangzefeng 

**Does this PR introduce a user-facing change?**:

```release-note

cloudcore, edgecore,edgesite,keadm support show detail version info.

```

### CODE REVIEW

**Comment by kadisi** [comment]
> I think it's time to add now, I will include it in the versioning doc.

@kevin-wangzefeng agree

**Comment by kevin-wangzefeng** [comment]
> Open questiong: for keadm, it's ok to make `version` as a command, but for cloudcore, edgecore and edgesite, shall we make it flag `--version` install of command `version`?

In kubernetes, to query the version of apiserver, scheduler etc., `--version` is used.
Only kubectl and kubeadm support `version` command.

**Comment by kadisi** [comment]
> In kubernetes, to query the version of apiserver, scheduler etc., --version is used.
Only kubectl and kubeadm support version command.

@kevin-wangzefeng ok, agree

File: cloud/cmd/cloudcore/app/version.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+
+// RunVersion provides the version information of kubeadm in format depending on arguments
+// specified in cobra.Command.
+func RunVersion(out io.Writer, cmd *cobra.Command) error {
+	v := version.Get()
+
+	const flag = "output"
+	of, err := cmd.Flags().GetString(flag)
+	if err != nil {
+		klog.Fatalf("error accessing flag %s for command %s: %v", flag, cmd.Name(), err)
```
Comment (subpathdev) [inline cloud/cmd/cloudcore/app/version.go]: (non blocking)
I think it would be better to replace `Fatalf` with `Errorf` and `return err`; I think this could increase the readability. Thoughts?

File: cloud/cmd/cloudcore/app/version.go [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+		}
+		fmt.Fprintln(out, string(y))
+	case "json":
+		y, err := json.MarshalIndent(&v, "", "  ")
+		if err != nil {
+			return err
+		}
+		fmt.Fprintln(out, string(y))
+	default:
+		return errors.Errorf("invalid output format: %s", of)
```
Comment (subpathdev) [inline cloud/cmd/cloudcore/app/version.go]: please replace `errors.Errorf` with `fmt.Errorf`

File: cloud/cmd/cloudcore/app/version.go (hunk 1 above)
Comment (kadisi) [reply cloud/cmd/cloudcore/app/version.go]: @subpathdev  as @kevin-wangzefeng  said, we need to make flag `--version` install of command `version`, so this file has been deleted

File: cloud/cmd/cloudcore/app/version.go (hunk 2 above)
Comment (kadisi) [reply cloud/cmd/cloudcore/app/version.go]: @subpathdev this file has been deleted

**Comment by kadisi** [comment]
@kevin-wangzefeng @subpathdev @fisherxu 

for keadm, 
```
# keadm version

version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-286+4b36cde6dbed8f", GitCommit:"4b36cde6dbed8fbd4ac9b0314e20102027e722ed", GitTreeState:"clean", BuildDate:"2019-08-21T08:03:59Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}

# keadm version -o short
v1.0.0-286+4b36cde6dbed8f

# keadm version -o json
{
  "major": "1",
  "minor": "0+",
  "gitVersion": "v1.0.0-286+4b36cde6dbed8f",
  "gitCommit": "4b36cde6dbed8fbd4ac9b0314e20102027e722ed",
  "gitTreeState": "clean",
  "buildDate": "2019-08-21T08:03:59Z",
  "goVersion": "go1.12.7",
  "compiler": "gc",
  "platform": "linux/amd64"
}

#keadm version -o yaml
major: "1"
minor: 0+
gitversion: v1.0.0-286+4b36cde6dbed8f
gitcommit: 4b36cde6dbed8fbd4ac9b0314e20102027e722ed
gittreestate: clean
builddate: "2019-08-21T08:03:59Z"
goversion: go1.12.7
compiler: gc
platform: linux/amd64

```

and for edgecore , cloudcore, edgeside 
```
#edgesite --version
Kubernetes v1.0.0-324+4f1161e3393ada

```

**Comment by fisherxu** [comment]
> #edgesite --version
Kubernetes v1.0.0-324+4f1161e3393ada

Kubernetes? @kadisi

**Comment by kadisi** [comment]
> Kubernetes? @kadisi

@fisherxu KubeEdge

File: edgesite/cmd/app/options/options.go [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
+func NewEdgeSiteOptions() *EdgeSiteOptions {
+	return &EdgeSiteOptions{}
+}
+
+func (o *EdgeSiteOptions) Flags() (fss *cliflag.NamedFlagSets) {
+	fss = &cliflag.NamedFlagSets{}
+	// TODO set EdgeSiteOptions field
+	//fs := fss.FlagSet("general")
+	return
```
Comment (subpathdev) [inline edgesite/cmd/app/options/options.go]: no return value?

File: keadm/app/cmd/version.go [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+		}
+		fmt.Fprintln(out, string(y))
+	case "json":
+		y, err := json.MarshalIndent(&v, "", "  ")
+		if err != nil {
+			return err
+		}
+		fmt.Fprintln(out, string(y))
+	default:
+		return errors.Errorf("invalid output format: %s", of)
```
Comment (subpathdev) [inline keadm/app/cmd/version.go]: can we use fmt.Errorf instead of errors.Errorf? It would decrease the count of dependencies

File: keadm/app/cmd/version.go [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+
+// fatal prints the message if set and then exits.
+func fatal(msg string, code int) {
+	if len(msg) > 0 {
+		// add newline if needed
+		if !strings.HasSuffix(msg, "\n") {
+			msg += "\n"
+		}
+
+		fmt.Fprint(os.Stderr, msg)
```
Comment (subpathdev) [inline keadm/app/cmd/version.go]: can we use klog.Error here? (I think we could remove the if condition above, if we are using klog)

File: edgesite/cmd/app/options/options.go (hunk 3 above)
Comment (kadisi) [reply edgesite/cmd/app/options/options.go]: fss is the return value

File: keadm/app/cmd/version.go (hunk 4 above)
Comment (kadisi) [reply keadm/app/cmd/version.go]: we refer to [kubernetes code ](https://github.com/kubernetes/kubernetes/blob/4495d09282265964ae217ab9976c4c4ff5945b7b/cmd/kubeadm/app/cmd/version.go#L86)

File: keadm/app/cmd/version.go (hunk 5 above)
Comment (kadisi) [reply keadm/app/cmd/version.go]: refet to [k8s](https://github.com/kubernetes/kubernetes/blob/21cdcd577609c039043903edfd4995077fc6b27d/cmd/kubeadm/app/util/error.go#L46)

**Comment by fisherxu** [comment]
@kadisi Some change to admission merged, need a rebase here

File: cloud/cmd/cloudcore/app/version.go [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+
+const (
+	// DefaultErrorExitCode defines exit the code for failed action generally
+	DefaultErrorExitCode = 1
+)
+
+func NewCmdVersion() *cobra.Command {
+	cmd := &cobra.Command{
+		Use:   "version",
+		Short: "Print the version of kubeadm",
```
Comment (fisherxu) [inline cloud/cmd/cloudcore/app/version.go]: cloudcore

File: cloud/cmd/admission/app/options/options.go [hunk 7]
```diff
@@ -1,11 +1,26 @@
+/*
+  pyright 2019 The KubeEdge Authors.
```
Comment (fisherxu) [inline cloud/cmd/admission/app/options/options.go]: copyright    ;;;-)

File: cloud/cmd/cloudcore/app/options/options.go [hunk 8]
```diff
@@ -0,0 +1,35 @@
+/*
+  pyright 2019 The KubeEdge Authors.
```
Comment (fisherxu) [inline cloud/cmd/cloudcore/app/options/options.go]: copyright

File: edge/cmd/edgecore/app/options/options.go [hunk 9]
```diff
@@ -0,0 +1,35 @@
+/*
+  pyright 2019 The KubeEdge Authors.
```
Comment (fisherxu) [inline edge/cmd/edgecore/app/options/options.go]: copyright

File: edgesite/cmd/app/options/options.go [hunk 10]
```diff
@@ -0,0 +1,35 @@
+/*
+  pyright 2019 The KubeEdge Authors.
```
Comment (fisherxu) [inline edgesite/cmd/app/options/options.go]: copyright

File: cloud/cmd/cloudcore/app/version.go (hunk 6 above)
Comment (fisherxu) [reply cloud/cmd/cloudcore/app/version.go]: ignore this

File: cloud/cmd/admission/admission.go [hunk 11]
```diff
@@ -1,19 +1,12 @@
...
-	"k8s.io/klog"
-
 	"github.com/kubeedge/kubeedge/cloud/cmd/admission/app"
 )
 
 func main() {
-	klog.InitFlags(nil)
-	pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
-
 	command := app.NewAdmissionCommand()
```
Comment (fisherxu) [inline cloud/cmd/admission/admission.go]: Seems don't init klog here?

File: edge/cmd/edgecore/edgecore.go [hunk 12]
```diff
@@ -1,19 +1,12 @@
...
-	"k8s.io/klog"
-
 	"github.com/kubeedge/kubeedge/edge/cmd/edgecore/app"
 )
 
 func main() {
-	klog.InitFlags(nil)
-	pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
-
 	command := app.NewEdgeCoreCommand()
```
Comment (fisherxu) [inline edge/cmd/edgecore/edgecore.go]: Need init klog?

File: edgesite/cmd/edgesite.go [hunk 13]
```diff
@@ -1,19 +1,12 @@
...
-	"k8s.io/klog"
-
 	"github.com/kubeedge/kubeedge/edgesite/cmd/app"
 )
 
 func main() {
-	klog.InitFlags(nil)
-	pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
-
 	command := app.NewEdgeSiteCommand()
```
Comment (fisherxu) [inline edgesite/cmd/edgesite.go]: ditto

File: vendor/modules.txt [hunk 14]
```diff
@@ -922,7 +926,7 @@ k8s.io/csi-translation-lib
 k8s.io/klog
 # k8s.io/kube-openapi v0.0.0-20190718094010-3cf2ea392886
 k8s.io/kube-openapi/pkg/util/proto
-# k8s.io/kubernetes v1.15.2
```
Comment (fisherxu) [inline vendor/modules.txt]: Can we update the version in edgecore config file to 1.15.3 now...

**Comment by fisherxu** [comment]
Overall look good, thanks!! @kadisi  See the comments above, and the golint in admission need fixed :)

File: cloud/cmd/admission/app/options/options.go (hunk 7 above)
Comment (kadisi) [reply cloud/cmd/admission/app/options/options.go]: done

File: edge/cmd/edgecore/edgecore.go (hunk 12 above)
Comment (kadisi) [reply edge/cmd/edgecore/edgecore.go]: done

File: vendor/modules.txt (hunk 14 above)
Comment (kadisi) [reply vendor/modules.txt]: done

**Comment by sids-b** [comment]
Thanks @kadisi 

/approve

/hold
for @kevin-wangzefeng approval

**Comment by fisherxu** [comment]
/hold cancel
Let's got merged first, if have any other issue, just fixed in follow up PR.
