### PR TITLE
fix issue minor version of full managed k8s instances

### LINKED ISSUE #1546: Error parsing EKS k8s minor version
**What happened**:
AWS EKS clusters use a non-standard minor version in their API, so invoking `kubectl version` will return:
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

So when I invoke `keadm init` I get back `Error: Your minor version of K8s is lower than 11, please reinstall newer version`

**What you expected to happen**:
Be able to install kubeedge

**How to reproduce it (as minimally and precisely as possible)**:
Create any AWS EKS cluster. I contacted support, all their versions have a plus symbol in their minor version.

### PR DESCRIPTION
**Pull request by subpathdev**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix extracting minor version of full managed k8s instances

**Which issue(s) this PR fixes**:
Fixes #1546

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
- enabled unit-test in keadm
```

### CODE REVIEW

**Comment by subpathdev** [comment]
I will write a unit-test to avoid this issue in feature

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 1]
```diff
@@ -293,7 +295,17 @@ func isK8SComponentInstalled(kubeConfig, master string) error {
...
+	return checkKubernetesVersion(serverVersion)
+}
+
+func checkKubernetesVersion(serverVersion *version.Info) error {
+	reg := regexp.MustCompile(`[[:digit:]]*`)
+	minorVersion := reg.FindString(serverVersion.Minor)
+
+	k8sMinorVersion, err := strconv.Atoi(minorVersion)
+	if err != nil {
+		return fmt.Errorf("Could not parse the minor version of K8s, please open an issue on https://github.com/kubeedge/kubeedge with the following error message: %s", err)
```
Comment (fisherxu) [inline keadm/cmd/keadm/app/cmd/util/common.go]:
```suggestion
		return fmt.Errorf("Could not parse the minor version of K8s, error: %s", err)
```
How about the log errors focusing on the error itself? :)

File: keadm/cmd/keadm/app/cmd/util/common_test.go [hunk 2]
```diff
@@ -0,0 +1,72 @@
+/*
+Copyright 2019 The Kubeedge Authors.
```
Comment (fisherxu) [inline keadm/cmd/keadm/app/cmd/util/common_test.go]: 2020
