### PR TITLE
Handled case in bluetooth mapper with no converter information while reading

### LINKED ISSUE #734: Bluetooth mapper trying to use data converter for reading even when data converter not specified
**What happened**:
Bluetooth mapper trying to use data converter for reading even when data converter is not specified in the device model

**What you expected to happen**:
Bluetooth mapper should report the data that is read as it is without converting it if no conversion data is specified

**How to reproduce it (as minimally and precisely as possible)**:
Setup Kubeedge
Apply device model and device for bluetooth without any converter information
Run bleutooth mapper

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR handles case in bluetooth mapper when no data converter is given while reading

**Which issue(s) this PR fixes**:

Fixes #734

### CODE REVIEW

File: device/bluetooth_mapper/configuration/config.go [hunk 1]
```diff
@@ -147,7 +147,8 @@ func (b *BLEConfig) Load() error {
 					return errors.New("Error in unmarshalling data property visitor configuration: " + err.Error())
 				}
 				action.Operation.CharacteristicUUID = bluetoothPropertyVisitor.CharacteristicUUID
-				if !reflect.DeepEqual(bluetoothPropertyVisitor.BluetoothDataConverter, nil) {
+				newBluetoothVisitorConfig:=VisitorConfigBluetooth{}
```
Comment (rohitsardesai83) [inline device/bluetooth_mapper/configuration/config.go]: gofmt please.

Comment (sujithsimon22) [reply device/bluetooth_mapper/configuration/config.go]: done
