### PR TITLE
Makefile changes to make both cloud and edge_core binaries

### LINKED ISSUE #338: build: Running `make` builds only edge_core.
**What happened**:
When I run "make" from the root folder i.e kubedge/kubedge , it only  compiles edge_core.

**What you expected to happen**:
When I run make, it should first build cloud , followed by edge code.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
$cd src/github.com/kubeedge/kubeedge
$make
cd edge && make
make[1]: Entering directory '/home/root1/go/src/github.com/kubeedge/kubeedge/edge'
go build cmd/edge_core.go
make[1]: Leaving directory '/home/root1/go/src/github.com/kubeedge/kubeedge/edge'
```

**Anything else we need to know?**:
NA

**Environment**: Ubuntu 16.04 LTS
- KubeEdge version: HEAD

### PR DESCRIPTION
**Pull request by srivatsav123**
These changes will build both cloud and edge binaries when you do make

**What type of PR is this?**
This PR will build both cloud and edge binaries

 /kind test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #338 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
Why have we made changes to remove individual cloud and edge builds ?? If a user wants to just build and use edge with IEF, he can run build edge command only.

**Comment by srivatsav123** [comment]
@sids-b - hmm makes sense to add individual edge and cloud builds in Makefile i will change it...But In travis.yml instead of adding two different build(one for cloud and edge)..only one build (make) will be better!!! what's your opinion on this??

File: Makefile [hunk 1]
```diff
@@ -1,6 +1,7 @@
-# make edge_core
-.PHONY: edge_core
-edge_core:
+# make cloud_edge_components
+.PHONY: cloud_edge_components
+cloud_edge_components:
```
[the remark this answers is not in the document]
Comment (srivatsav123) [reply Makefile]: Above command is to build both cloud and edge components together..So i kept cloud_edge_components...If we keep only cloud user might be confused!!
cloud_edge_components -> cloud-edge-components ???is it ok

File: Makefile [hunk 2]
```diff
@@ -25,6 +26,12 @@ edge_cross_build:
 edge_small_build:
 	cd edge && $(MAKE) small_build
 
+# build edge_core
```
[the remark this answers is not in the document]
Comment (srivatsav123) [reply Makefile]: ok

File: tests/e2e/scripts/execute.sh [hunk 3]
```diff
@@ -25,8 +25,7 @@ if [ ! -d "/var/lib/edged" ]; then
 fi
 
 #run the edge_core and edgecontroller bin to run the E2E
-make edge_core
-make edgecontroller
+make #builds cloud and edgecore components
```
[the remark this answers is not in the document]
Comment (srivatsav123) [reply tests/e2e/scripts/execute.sh]: ok

File: Makefile (hunk 2 above)
[the remark this answers is not in the document]
Comment (srivatsav123) [reply Makefile]: Binary will be created as edge_core not edge-core... so i feel it to keep as edge_core only

File: Makefile [hunk 4]
```diff
@@ -1,6 +1,6 @@
-# make cloud_edge_components
-.PHONY: cloud_edge_components
-cloud_edge_components:
+# make cloud-edge-components
+.PHONY: cloud-edge-components
+cloud-edge-components:
```
Comment (m1093782566) [inline Makefile]: what about `make all` so to `all` here?

Comment (m1093782566) [reply Makefile]: And then run `make all WHAT={path to component}` to build individual components.

Comment (srivatsav123) [reply Makefile]: @m1093782566 No it will be very complicated to implement .. If we had many components as in kubernetes cmd folder(apiserver,scheduler,kubelet, etc.....)then there was a need to implement **make all WHAT={path to component}** ex: make all WHAT=cmd/kubelet GOFLAGS=-v to compile binaries and to run test cases for individual package....In our case we have only 2 components to build, And also **edge** and **cloud** are in different  folder location ...I think the approach we are following is fine...   cc @rohitsardesai83 @sids-b

Comment (m1093782566) [reply Makefile]: > In our case we have only 2 components to build

I am sure we will add more components in the cloud.

Comment (srivatsav123) [reply Makefile]: > I am sure we will add more components in the cloud.
> ok then it makes sense

Comment (srivatsav123) [reply Makefile]: Screenshot from 2019-04-11 20-47-24

Comment (srivatsav123) [reply Makefile]: @m1093782566 -Please review

File: Makefile [hunk 5]
```diff
@@ -1,7 +1,22 @@
...
-.PHONY: edge_core
-edge_core:
+# make all builds both cloud and edge binaries
+.PHONY: all  
+ifeq ($(WHAT),)
+all:
+	cd cloud/edgecontroller && $(MAKE)
+	cd edge && $(MAKE)
+else ifeq ($(WHAT),cloud)
+#make all what=cloud,build cloud binary
```
Comment (m1093782566) [inline Makefile]: nit:

```
# make all WHAT=cloud, build cloud binary
```

File: Makefile [hunk 6]
```diff
@@ -1,7 +1,22 @@
...
+all:
+	cd cloud/edgecontroller && $(MAKE)
+else ifeq ($(WHAT),edge)
+all:
+#make all what=edge, build edge binary
```
Comment (m1093782566) [inline Makefile]: nit:

```
# make all WHAT=edge, build edge binary
```

File: Makefile [hunk 7]
```diff
@@ -1,7 +1,22 @@
...
 	cd edge && $(MAKE)
+else
+#invalid entry
+all:
+	@echo $S"invalid option please choose to build either cloud,edge or both"
```
Comment (m1093782566) [inline Makefile]: nit:

```
cloud, edge or bot
```

File: README.md [hunk 8]
```diff
@@ -138,11 +138,18 @@ cd $GOPATH/src/github.com/kubeedge/kubeedge
 
 #### Run as a binary
 
++ Build Cloud and edge
+
+    ```shell
+    cd $GOPATH/src/github.com/kubeedge/kubeedge
+     make or `make all `
```
Comment (m1093782566) [inline README.md]: I think provide an option is enough here. So please either choose `make` or `make all`.

File: README.md [hunk 9]
```diff
@@ -138,11 +138,18 @@ cd $GOPATH/src/github.com/kubeedge/kubeedge
...
+    ```
+
 + Build Cloud
 
     ```shell
-    cd $GOPATH/src/github.com/kubeedge/kubeedge/cloud/edgecontroller
-    make # or `make edgecontroller`
+    cd $GOPATH/src/github.com/kubeedge/kubeedge
+     `make all WHAT=cloud`
```
Comment (m1093782566) [inline README.md]: Please remove the ``.

File: README.md (hunk 8 above)
Comment (srivatsav123) [reply README.md]: ok will chose make

File: README.md (hunk 9 above)
Comment (srivatsav123) [reply README.md]: ok

File: Makefile (hunk 7 above)
Comment (srivatsav123) [reply Makefile]: ok

File: Makefile (hunk 5 above)
Comment (srivatsav123) [reply Makefile]: ok

File: Makefile (hunk 6 above)
Comment (srivatsav123) [reply Makefile]: ok
