### PR TITLE
Edgesite code refactored - removed duplicated code

### LINKED ISSUE #531: Consolidate the controller code for kubeedge edgenode and edgesite
**What happened**:
Currently we dup-ed controller code for edgenode and edgesite. 

**What you expected to happen**:
To enable code reuse, we should remove the un-necessary redundancy and prevent too many branching in the code. 

The proposal is to keep the controller/manager code for edge and edgesite where edgesite will query pod/configmap/secret metadata specifically for the node; and edge code will query all but route the message to different nodes. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by samy2019**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Removes duplicated controller code for edgesite.

Which issue(s) this PR fixes:
Fixes #531

Special notes for your reviewer:
PR #591 was already raised earlier, but it had some issues while reducing the commits. Hence created a new one. Changes are same.

### CODE REVIEW

**Comment by m1093782566** [comment]
@samy2019 As I mentioned earlier, you should learn some most-used git skills.

Please don't close the PR in the future as it will lose the comments.

File: cloud/pkg/controller/config/kube.go [hunk 1]
```diff
@@ -52,4 +64,24 @@ func init() {
...
+		KubeNodeName = name
+	}
+	log.LOGGER.Infof("Controller kube Node Name: %s", KubeNodeName)
+
+	if es, err := config.CONFIG.GetValue("metamanager.edgesite").ToBool(); err != nil {
+		EdgeSiteEnabled = false
+	} else {
+		EdgeSiteEnabled = es
+	}
+	log.LOGGER.Infof(" EdgeSite is %s ", EdgeSiteEnabled)
```
Comment (rohitsardesai83) [inline cloud/pkg/controller/config/kube.go]: %s -> %t ? since its a bool.

File: cloud/pkg/controller/messagelayer/util.go [hunk 2]
```diff
@@ -34,26 +44,71 @@ func GetNodeID(msg model.Message) (string, error) {
...
+	var res string
+	var index uint8
+	if config.EdgeSiteEnabled {
+		res = sli[controller.EdgeSiteResourceNamespaceIndex]
+		index = controller.EdgeSiteResourceNamespaceIndex
+	} else {
+		res = sli[controller.ResourceNamespaceIndex]
+		index = controller.ResourceNamespaceIndex
+	}
+	log.LOGGER.Infof("The namespace is %s, %d", res, index)
```
Comment (rohitsardesai83) [inline cloud/pkg/controller/messagelayer/util.go]: do we need this log ? can it be at debug level ? also the format of message can be improved to indicate the index.

File: cloud/pkg/controller/config/kube.go (hunk 1 above)
Comment (samy2019) [reply cloud/pkg/controller/config/kube.go]: Done. Thanks

File: cloud/pkg/controller/messagelayer/util.go (hunk 2 above)
Comment (samy2019) [reply cloud/pkg/controller/messagelayer/util.go]: Done. Thanks

File: cloud/pkg/controller/controller/downstream.go [hunk 3]
```diff
@@ -215,7 +228,15 @@ func NewDownstreamController() (*DownstreamController, error) {
 		return nil, err
 	}
 
-	podManager, err := manager.NewPodManager(cli, v1.NamespaceAll)
+	var nodeName = ""
+	if config.EdgeSiteEnabled {
+		if config.KubeNodeName == "" {
+			return nil, fmt.Errorf("kubeEdge node name is not provided in edgesite controller configuration")
```
Comment (subpathdev) [inline cloud/pkg/controller/controller/downstream.go]: I think you should use log.LOGGER.Errorf and not fmt.Errorf.

Comment (samy2019) [reply cloud/pkg/controller/controller/downstream.go]: This is ok to do fmt.Errorf() because the caller of NewDownstreamController(), is reading this error and logging it. So need to log same information twice.

Comment (subpathdev) [reply cloud/pkg/controller/controller/downstream.go]: sry I look over the return value of NewDownstreamController

**Comment by sids-b** [comment]
We are deleting a lot of duplicate code. Please resolve conflicts and squash the commits. PR looks Good to me :)

**Comment by rohitsardesai83** [comment]
@m1093782566 , please review.

**Comment by sids-b** [comment]
@samy2019 , please squash the commits. The PR looks good to me
