### PR TITLE
normalize the hostname in fucntion GetHostname

### LINKED ISSUE #5391: EdgeCore has different behavior in generating node name compared to kubelet.
**What happened**:

EdgeCore and kubelet generates different node names.

**What you expected to happen**:

EdgeCore and kubelet generates the same node.

**How to reproduce it (as minimally and precisely as possible)**:

Install edgecore on a server with uppercase hostname.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): 15.1
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

Kubelet uses the lower case of hostname for node name.

```golang
// https://github.com/kubernetes/kubernetes/blob/b98e47dd80166935117f890b437c8e30a91da173/staging/src/k8s.io/component-helpers/node/util/hostname.go
func GetHostname(hostnameOverride string) (string, error) {
	hostName := hostnameOverride
	if len(hostName) == 0 {
		nodeName, err := os.Hostname()
		if err != nil {
			return "", fmt.Errorf("couldn't determine hostname: %w", err)
		}
		hostName = nodeName
	}

	// Trim whitespaces first to avoid getting an empty hostname
	// For linux, the hostname is read from file /proc/sys/kernel/hostname directly
	hostName = strings.TrimSpace(hostName)
	if len(hostName) == 0 {
		return "", fmt.Errorf("empty hostname is invalid")
	}

	return strings.ToLower(hostName), nil
}
```

However, edge core generates node name by hostname without a `ToLower()` step.

```golang
// https://github.com/kubeedge/kubeedge/blob/master/pkg/util/util.go
func GetHostname() string {
	hostnameOverride, err := os.Hostname()
	if err != nil {
		return constants.DefaultHostnameOverride
	}
	msgs := validation.ValidateNodeName(hostnameOverride, false)
	if len(msgs) > 0 {
		return constants.DefaultHostnameOverride
	}
	return hostnameOverride
}
```

If there is a node with hostname `Abc`, the node name generated by kubelet is `abc` while edgecore name it `default-edge-node`.

The difference may lead to some compatibility issues when some nodes are migrated from kubelet to kubeedge.

### PR DESCRIPTION
**Pull request by spambot000**
Because hostname is case-insensitive, normalize it before coverting to a DNS subdomain name.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Kubeedge generates default node name by hostname if it is a valid DNS subdomain. The default node name will be `default-edge-node` if hostname contains uppercase letters, which may lead to compatibility issues when nodes are migrated from kubelet to kubeedge.

**Which issue(s) this PR fixes**：

Fixes #5391

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

yes
```release-note
The default name of node which has a uppercase hostname is changed from `default-edge-node` to lowercase hostname.
```

### CODE REVIEW

File: pkg/util/util.go [hunk 1]
```diff
@@ -135,6 +135,9 @@ func GetHostname() string {
 	if err != nil {
 		return constants.DefaultHostnameOverride
 	}
+	// Hostname should be normailzied because it's case-insensitive
```
Comment (Shelley-BaoYue) [inline pkg/util/util.go:138]: Thx for your contributions!  Can we call `GetHostName` func of kubernetes mentioned in the issue https://github.com/kubeedge/kubeedge/issues/5391 here?   In this way, if there is any change in Kubernetes, it can be directly synchronized.

Comment (spambot000) [reply pkg/util/util.go]: Yes, it's the better implementation.

File: pkg/util/util.go [hunk 2]
```diff
@@ -26,6 +26,7 @@ import (
 	"strings"
 
 	utilnet "k8s.io/apimachinery/pkg/util/net"
+	nodeutil "k8s.io/component-helpers/node/util"
```
Comment (Shelley-BaoYue) [inline pkg/util/util.go:29]: Because the import lib has been updated, you need to execute `make verify` and commit the changes to update go.mod and vendor.

Comment (spambot000) [reply pkg/util/util.go:29]: Fixed. I ran the command under a directory that didn't contains the `.git` dir.

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm 
cc @WillardHu @fisherxu
