### PR TITLE
Fixed recreate secret when etcd error

### LINKED ISSUE #6052: cloudcore recreate secret when etcd error
version: all cloudcore

In founction createCAToSecret and createCertsToSecret, the error of GerSecert may be NotFound Or ETCD request error, secret will be recreate when ETCD error and then all edgecore cannot connect to cloudcore.

createCAToSecret 和 createCertsToSecret 函数中 GetSecret 函数的错误没有区分不存在和ETCD故障，如果是后者，证书密钥等会被重新生成，导致已经部署好的环境所有边端再也连不上了。

```
createCAToSecret
createCertsToSecret

// Check whether the ca exists in the secret
    caSecret, err := client.GetSecret(ctx, CaSecretName, constants.SystemNamespace)
    if err != nil {
	    klog.Info("Ca and CaKey don't exist in the secret, and will be created by CloudCore")
	    h := certs.GetCAHandler(certs.CAHandlerTypeX509)
	    pk, err := h.GenPrivateKey()
	    if err != nil {
		    return err
	    }
	......
```

### PR DESCRIPTION
**Pull request by LRaito**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixed the wrong duplicate generation of certificate files if etcd fails when cloudcore start, or the old certificate will be overwrite then all edgecore will be not Ready

**Which issue(s) this PR fixes**:

Fixes #6052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: cloud/pkg/cloudhub/servers/httpserver/pre_server.go [hunk 1]
```diff
@@ -63,6 +64,11 @@ func createCAToSecret(ctx context.Context) error {
 		// Check whether the ca exists in the secret
 		caSecret, err := client.GetSecret(ctx, CaSecretName, constants.SystemNamespace)
 		if err != nil {
+			if !apierror.IsNotFound(err) {
+				klog.Errorf("get secret: %s error: %v", CaSecretName, err)
+				return err
```
Comment (WillardHu) [inline cloud/pkg/cloudhub/servers/httpserver/pre_server.go:69]:
```go
return fmt.Errorf("get secret: %s error: %v", CaSecretName, err)
```
This makes it easier for us to trace errors. The log have no id to associated with the error stack.

File: cloud/pkg/cloudhub/servers/httpserver/pre_server.go [hunk 2]
```diff
@@ -106,6 +112,11 @@ func createCertsToSecret(ctx context.Context) error {
 		// Check whether the CloudCore certificates exist in the secret
 		cloudSecret, err := client.GetSecret(ctx, CloudCoreSecretName, constants.SystemNamespace)
 		if err != nil {
+			if !apierror.IsNotFound(err) {
+				klog.Errorf("get secret: %s error: %v", CloudCoreSecretName, err)
+				return err
```
Comment (WillardHu) [inline cloud/pkg/cloudhub/servers/httpserver/pre_server.go:117]: Ditto.

**Review by wbc6080 — COMMENTED** [review]
Plz fill in the content of **What this PR does / why we need it:** . Thanks
image

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve
Thanks for your contributions! You can cherry-pick this pr to release 1.16-1.19, ref to https://kubeedge.io/docs/developer/cherry_pick
