### PR TITLE
Fix/tls min version cloudhub

### LINKED ISSUE #6387: Add a mininum TLS version (at least 1.2) for CloudHub component
**What would you like to be added/modified**:

Add a mininum TLS version (at least 1.2) for CloudHub component of the CloudCore

**Why is this needed**:
Some vulnerability scanning tools such as Nessus report the CloudHub port (by default 10002) as vulnerable because the use of TLS 1.1 isn't explicitly disabled.

A similar work was done for the Stream Server in #3764

### PR DESCRIPTION
**Pull request by NishantSinghhhhh**
What type of PR is this?
/kind feature

What this PR does / why we need it:
This PR enforces a minimum TLS version of 1.2 for the CloudHub HTTP server component. By explicitly setting MinVersion: tls.VersionTLS12 in the TLS configuration, it disables older, insecure TLS versions (1.0, 1.1) that expose the CloudHub port to vulnerabilities reported by scanning tools. This improves the security posture of the CloudHub component.

Which issue(s) this PR fixes:
Fixes #6387

Special notes for your reviewer:
The TLS configuration was updated in cloud/pkg/cloudhub/servers/httpserver/server.go to include the minimum TLS version. Testing with openssl s_client confirms that TLS 1.1 connections are no longer accepted.

Does this PR introduce a user-facing change?:
No

### CODE REVIEW

**Comment by NishantSinghhhhh** [comment]
Hi @threestoneliu and @XJangel, 

I have submitted a PR addressing the TLS minimum version issue for the CloudHub component in KubeEdge (related to Issue #6387). When you have some time, could you please review the changes? Your feedback would be greatly appreciated!

Thanks in advance!

**Comment by WillardHu** [comment]
Thanks for your contribution. Please use `git rebase -i HEAD~2` to merge two commits with the same name.

File: cloud/pkg/cloudhub/servers/httpserver/server.go [hunk 1]
```diff
@@ -50,8 +50,9 @@ func StartHTTPServer() error {
 		TLSConfig: &tls.Config{
 			Certificates: []tls.Certificate{cert},
 			ClientAuth:   tls.RequestClientCert,
+			MinVersion:   tls.VersionTLS12,
 		},
-	}
+	}
```
Comment (WillardHu) [inline cloud/pkg/cloudhub/servers/httpserver/server.go]: Please remove the invalid spaces

`cloud/pkg/cloudhub/servers/httpserver/server.go:55: File is not `gofmt`-ed with `-s` (gofmt)`

**Comment by NishantSinghhhhh** [comment]
@WillardHu , I have added the requested changed, can you tell me if any more changes are required in this PR

**Comment by NishantSinghhhhh** [comment]
@WillardHu , I have added the requested changed, can you tell me if any more changes are required in this PR

**Comment by NishantSinghhhhh** [comment]
@WillardHu can you please tell me what more should so that I can merge this PR

**Comment by WillardHu** [comment]
> @WillardHu can you please tell me what more should so that I can merge this PR

Just waiting for a maintainer to review and approve this PR.

**Comment by NishantSinghhhhh** [comment]
@wbc6080 , can you please review this PR ?

**Comment by NishantSinghhhhh** [comment]
@wbc6080, @XmchxUp @threestoneliu @XJangel   can you please review this PR ?
