### PR TITLE
Fix the bug #884

### LINKED ISSUE #884: Edge_core crashing if there is no bridge decvice when starting
**What happened**:
Edge_core crashing if there is no bridge decvice when starting

**What you expected to happen**:
Edge_core waiting for creating bridge device when starting

**How to reproduce it (as minimally and precisely as possible)**:
delete the bridge device "docker0", and restarting the edge_core program.

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by arcanique**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug

**What this PR does / why we need it**:
>
> Fix the bug #884

**Which issue(s) this PR fixes**:

Fixes #884 

**Special notes for your reviewer**:

### CODE REVIEW

File: edgemesh/pkg/server/dns.go [hunk 1]
```diff
@@ -76,20 +76,26 @@ func DnsStart() {
...
 func getDnsServer() (net.IP, error) {
-	ifaces, err := net.InterfaceByName(inter)
-	if err != nil {
-		return nil, err
-	}
+	for {
+		ifaces, err := net.InterfaceByName(inter)
+		if err != nil {
+			log.LOGGER.Warnf("get interface error : %s", err)
+			time.Sleep(time.Second * 5)
```
Comment (Baoqiang-Zhang) [inline edgemesh/pkg/server/dns.go]: why sleep here?

File: edgemesh/pkg/server/dns.go [hunk 2]
```diff
@@ -76,20 +76,26 @@ func DnsStart() {
...
-		if ip, inet, _ := net.ParseCIDR(addr.String()); len(inet.Mask) == 4 {
-			return ip, nil
+		for _, addr := range addrs {
+			if ip, inet, _ := net.ParseCIDR(addr.String()); len(inet.Mask) == 4 {
+				return ip, nil
+			}
 		}
+
+		log.LOGGER.Warnf("the interface " + inter + " has not config ip of version 4")
+		time.Sleep(time.Second * 5)
```
Comment (Baoqiang-Zhang) [inline edgemesh/pkg/server/dns.go]: ditto

File: edgemesh/pkg/server/dns.go (hunk 1 above)
Comment (arcanique) [reply edgemesh/pkg/server/dns.go]: The main reason for this bug is that containerd will only create network devices when the Pod is first created. Therefore, during the period of edge_core startup, it will always loop execution. The purpose of adding sleep is to make the cpu not too high. When you deploy the first Pod, this function will detect the corresponding device and exit normally.

File: edgemesh/pkg/server/dns.go (hunk 2 above)
Comment (arcanique) [reply edgemesh/pkg/server/dns.go]: The reason is the same as above.

File: edgemesh/pkg/server/dns.go (hunk 1 above)
Comment (rohitsardesai83) [reply edgemesh/pkg/server/dns.go]: can we reduce the sleep time ? 5 seconds looks high.

Comment (arcanique) [reply edgemesh/pkg/server/dns.go]: I can reduce this time to 3 seconds.
