### PR TITLE
use value interface of goarchaius config framework to get mqtt mode

### LINKED ISSUE #249: panics if using environment variable (mqtt.mode) to overwrite yaml config of edge core
**What happened**:

edge core process panics. (if mqtt.mode config entry is overwritten by using environment variable)

**What you expected to happen**:

parse configs succeeded without any panic.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
export mqtt.mode=0
./edge_core
```

**Anything else we need to know?**:

the goarchaius config framework parse yaml config into a `map[string]interface{}`. so if a config value in yaml is int, then the parsed object is an int what can directly cast to int. But the overwritten value of environment variable is always a string.

**Environment**:
- KubeEdge version: v0.2
- Hardware configuration: irrelevant
- OS (e.g. from /etc/os-release): irrelevant
- Kernel (e.g. `uname -a`): irrelevant
- Others: irrelevant

### PR DESCRIPTION
**Pull request by tedli**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

Use value interface of goarchaius config framework to get mqtt mode. The original logic cast directly to int, it may panic if the underneath value is not an int, this happens when using environment variable overwriting config entry, the value always be a string. The value interface of goarchaius provides many handy `ToXX` methods that can handle this well.

**Which issue(s) this PR fixes**:

Fixes #249 

**Special notes for your reviewer**:

The `mqtt.mode` config entry was config by yaml by default, the yaml content is parsed into a

```golang
map[string]interface{}
```

so with `mqtt.mode` key, we can get the int value. However if we overwrite this config entry by environment variable, with the same key, we got a string literal of the number.

### CODE REVIEW

**Comment by tedli** [comment]
```golang
case nil:
	return 0, nil
```

`ToInt` returns `0`, if value of a config entry is `nil`, while `internalMqttMode` constant is also `0`.

File: edge/pkg/eventbus/event_bus.go [hunk 1]
```diff
@@ -3,7 +3,6 @@ package eventbus
 import (
 	"encoding/json"
 	"fmt"
-
```
Comment (sids-b) [inline edge/pkg/eventbus/event_bus.go]: nit: Please don't remove this blank line. It is used to seperate golang and vendor packages

Comment (tedli) [reply edge/pkg/eventbus/event_bus.go]: OK

**Comment by sids-b** [comment]
> ```go
> case nil:
> 	return 0, nil
> ```
> 
> `ToInt` returns `0`, if value of a config entry is `nil`, while `internalMqttMode` constant is also `0`.

You would hit the error case if there is no entry in the config file right ? Also we want default mode to be internalmqtt mode.

File: edge/pkg/eventbus/event_bus.go [hunk 2]
```diff
@@ -34,14 +34,13 @@ type eventbus struct {
...
 
 func init() {
-	mode := config.CONFIG.GetConfigurationByKey("mqtt.mode")
-	if mode == nil {
-		mode = internalMqttMode
-	}
-	if mode.(int) > externalMqttMode || mode.(int) < internalMqttMode {
+	mode, err := config.CONFIG.GetValue("mqtt.mode").ToInt()
+	if err != nil {
+		panic(err)
```
Comment (sids-b) [inline edge/pkg/eventbus/event_bus.go]: Is there a need to panic here ? If mode is not specified in config file, we can safely start with internalMqttMode

Comment (tedli) [reply edge/pkg/eventbus/event_bus.go]: OK

**Comment by tedli** [comment]
> > ```go
> > case nil:
> > 	return 0, nil
> > ```
> > 
> > 
> > `ToInt` returns `0`, if value of a config entry is `nil`, while `internalMqttMode` constant is also `0`.
> 
> You would hit the error case if there is no entry in the config file right ? Also we want default mode to be internalmqtt mode.

Indeed. Would write condition cases by hand be a good idea? Somethine like this:

```golang
mode := config.CONFIG.GetConfigurationByKey("mqtt.mode")
var mqttMode int
var ok bool
if mode == nil {
	mode = internalMqttMode
	mqttMode = internalMqttMode
} else {
	if mqttMode, ok = mode.(int); !ok {
		var err error
		if modeStr, ok := mode.(string); !ok {
			panic("mqtt.mode should be one of [0,1,2]")
		} else if mqttMode, err = strconv.Atoi(modeStr); err != nil {
			panic(err)
		}
	}
}
```

**Comment by sids-b** [comment]
> > > ```go
> > > case nil:
> > > 	return 0, nil
> > > ```
> > > 
> > > 
> > > `ToInt` returns `0`, if value of a config entry is `nil`, while `internalMqttMode` constant is also `0`.
> > 
> > 
> > You would hit the error case if there is no entry in the config file right ? Also we want default mode to be internalmqtt mode.
> 
> Indeed. Would write condition cases by hand be a good idea? Somethine like this:
> 
> ```go
> mode := config.CONFIG.GetConfigurationByKey("mqtt.mode")
> var mqttMode int
> var ok bool
> if mode == nil {
> 	mode = internalMqttMode
> 	mqttMode = internalMqttMode
> } else {
> 	if mqttMode, ok = mode.(int); !ok {
> 		var err error
> 		if modeStr, ok := mode.(string); !ok {
> 			panic("mqtt.mode should be one of [0,1,2]")
> 		} else if mqttMode, err = strconv.Atoi(modeStr); err != nil {
> 			panic(err)
> 		}
> 	}
> }
> ```
How about this ? I guess this solves the problem ?
```
mode, err := config.CONFIG.GetValue("mqtt.mode").ToInt()
	if err != nil || (mode > externalMqttMode || mode < internalMqttMode) {
		mode = 0
         }
```

**Comment by tedli** [comment]
> > > > ```go
> > > > case nil:
> > > > 	return 0, nil
> > > > ```
> > > > 
> > > > 
> > > > `ToInt` returns `0`, if value of a config entry is `nil`, while `internalMqttMode` constant is also `0`.
> > > 
> > > 
> > > You would hit the error case if there is no entry in the config file right ? Also we want default mode to be internalmqtt mode.
> > 
> > 
> > Indeed. Would write condition cases by hand be a good idea? Somethine like this:
> > ```go
> > mode := config.CONFIG.GetConfigurationByKey("mqtt.mode")
> > var mqttMode int
> > var ok bool
> > if mode == nil {
> > 	mode = internalMqttMode
> > 	mqttMode = internalMqttMode
> > } else {
> > 	if mqttMode, ok = mode.(int); !ok {
> > 		var err error
> > 		if modeStr, ok := mode.(string); !ok {
> > 			panic("mqtt.mode should be one of [0,1,2]")
> > 		} else if mqttMode, err = strconv.Atoi(modeStr); err != nil {
> > 			panic(err)
> > 		}
> > 	}
> > }
> > ```
> 
> How about this ? I guess this solves the problem ?
> 
> ```
> mode, err := config.CONFIG.GetValue("mqtt.mode").ToInt()
> 	if err != nil || (mode > externalMqttMode || mode < internalMqttMode) {
> 		mode = 0
>          }
> ```

I've corrected as you told.

**Comment by m1093782566** [comment]
@tedli Thanks for your PR. I would like to suggest you create an associated issue for easily tracking the progress.

File: edge/pkg/eventbus/event_bus.go [hunk 3]
```diff
@@ -34,14 +34,11 @@ type eventbus struct {
 }
 
 func init() {
-	mode := config.CONFIG.GetConfigurationByKey("mqtt.mode")
-	if mode == nil {
+	mode, err := config.CONFIG.GetValue("mqtt.mode").ToInt()
+	if err != nil || (mode > externalMqttMode || mode < internalMqttMode) {
```
Comment (m1093782566) [inline edge/pkg/eventbus/event_bus.go]: what about 

```
if err != nil || mode > externalMqttMode || mode < internalMqttMode {
  mode = internalMqttMode
}
```

Comment (tedli) [reply edge/pkg/eventbus/event_bus.go]: Done.
