### PR TITLE
Fix: The server could not find the requested resource

### LINKED ISSUE #2801: [AKE]The server could not find the requested resource
**What happened**:
MetaServer' local storage response error "the server could not find the requested resource" when there is no resource , rather than a empty list. It is inconsistent with API Server response.
- MetaServer
image
- APIServer
image

**What you expected to happen**:
Return empty list.
**How to reproduce it (as minimally and precisely as possible)**:
request metaserver an resource that has no instance in cluster.

**Environment**:
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.6.1

### PR DESCRIPTION
**Pull request by Rachel-Shao**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When applying for a resource without an instance in cluster, APIServer will return an empty list.
But MetaServer' local storage response error "the server could not find the requested resource" when there is no resource , rather than an empty list.

**Which issue(s) this PR fixes**:
Fixes #2801

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:
none

### CODE REVIEW

File: edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go [hunk 1]
```diff
@@ -148,9 +148,6 @@ func (s *imitator) List(ctx context.Context, key string) (Resp, error) {
 	if err != nil {
 		return Resp{}, err
 	}
-	if len(*results) == 0 {
-		return Resp{}, fmt.Errorf("the server could not find the requested resource")
-	}
```
Comment (fisherxu) [inline edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go:153]: This means when results is empty, just return an empty response, right?

**Review by fisherxu — COMMENTED** [review]
Please add more description for the PR and please use the meaningful commit message.

File: edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go (hunk 1 above)
Comment (Rachel-Shao) [reply edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go:153]: yes
