### PR TITLE
set load balance strategy from edge.yaml and tcp server listens on ip of interface docker0

### LINKED ISSUE #986: edgemesh listens to 0.0.0.0 and load balance strategy is hard-code
**What happened**:
1. The tcp server listens to ```0.0.0.0``` now
2. The load balance strategy is hard-code now

**What you expected to happen**:
1. The tcp server listens on ip of interface ```docker0```
2. The load balance strategy can be set from ```edge.yaml```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:1.0.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by Holt2016**
**What type of PR is this?**
/kind  bug

**What this PR does / why we need it**:
1.  The tcp server listens on ip of interface ```docker0```
2. The load balance strategy can be set from ```edge.yaml```

**Which issue(s) this PR fixes**:

Fixes #986

**Special notes for your reviewer**:

### CODE REVIEW

File: edgemesh/cmd/edgemesh.go [hunk 1]
```diff
@@ -29,8 +30,15 @@ func main() {
 	control.Init(opts)
 	opt := registry.Options{}
 	registry.DefaultServiceDiscoveryService = edgeregistry.NewServiceDiscovery(opt)
-	loadbalancer.InstallStrategy(loadbalancer.StrategyRandom, func() loadbalancer.Strategy {
-		return &loadbalancer.RandomStrategy{}
+	myStrategy := mconfig.CONFIG.GetConfigurationByKey("mesh.loadbalance.strategy-name").(string)
```
Comment (anyushun) [inline edgemesh/cmd/edgemesh.go]: No need to modify this file, these are duplicate codes, I will delete them

File: edgemesh/pkg/server/tcp.go [hunk 2]
```diff
@@ -15,12 +15,15 @@ import (
...
 func StartTCP() {
-	server := config.GetString("server", "0.0.0.0")
-	port := config.GetString("port", "8080")
-
-	log.LOGGER.Infof("start listening at %s:%s", server, port)
 
-	listener, err := net.Listen("tcp", server+":"+port)
+	server, err:= getIP()
+	if err != nil {
+		log.LOGGER.Errorf("TCP server start error : %s", err)
```
Comment (anyushun) [inline edgemesh/pkg/server/tcp.go]: ```startDnsServer``` return when got error, ```StartTCP``` should also return?

if return ip is nil, will got panic

File: edgemesh/pkg/server/ip.go [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+	"net"
+	"time"
+
+	"github.com/kubeedge/beehive/pkg/common/log"
+)
+
+// getIP returns the specific interface ip of version 4
+func getIP() (net.IP, error) {
+	for {
+		ifaces, err := net.InterfaceByName(inter)
```
Comment (subpathdev) [inline edgemesh/pkg/server/ip.go]: where is the variable inter defined? you will run in an error here

File: edgemesh/pkg/server/ip.go [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+		if err != nil {
+			return nil, err
+		}
+		addrs, _ := ifaces.Addrs()
+		for _, addr := range addrs {
+			if ip, inet, _ := net.ParseCIDR(addr.String()); len(inet.Mask) == 4 {
+				return ip, nil
+			}
+		}
+		log.LOGGER.Warnf("the interface" + inter + "have not config ip of version 4")
```
Comment (subpathdev) [inline edgemesh/pkg/server/ip.go]: same here

Comment (subpathdev) [reply edgemesh/pkg/server/ip.go]: please use `%s` instead of `+ inter +` the definition of the verbs can be found here: https://godoc.org/fmt

File: edgemesh/pkg/server/dns.go [hunk 5]
```diff
@@ -74,37 +74,13 @@ func DnsStart() {
...
-}
-
 // startDnsServer start the DNS Server
 func startDnsServer() {
 	// init meta client
 	c := context.GetContext(context.MsgCtxTypeChannel)
 	metaClient = client.New(c)
 	//get DNS server name
-	lip, err := getDnsServer()
+	lip, err := getIP()
```
Comment (subpathdev) [inline edgemesh/pkg/server/dns.go]: you can use something like: `getIP(inter)` to resolve my previous comments

**Comment by Holt2016** [comment]
> please address the comments

ok, I modified, please take a look again

File: edgemesh/pkg/server/ip.go [hunk 6]
```diff
@@ -0,0 +1,26 @@
+package server
+
+import (
+	"net"
+	"time"
+
+	"github.com/kubeedge/beehive/pkg/common/log"
+)
+var inter = "docker0"
```
Comment (subpathdev) [inline edgemesh/pkg/server/ip.go]: I prefer the usage of const here; (non blocking)

**Comment by subpathdev** [comment]
sorry for the delay of review;
ping @anyushun, @edisonxiang  for review,

File: edgemesh/pkg/server/tcp.go (hunk 2 above)
Comment (sids-b) [reply edgemesh/pkg/server/tcp.go]: +1

File: edgemesh/cmd/edgemesh.go (hunk 1 above)
Comment (Holt2016) [reply edgemesh/cmd/edgemesh.go]: I have modified, please take a look again

**Comment by sids-b** [comment]
/cc @qizha @anyushun

for review
