### PR TITLE
use nodeIP initialization in Kubelet 

### LINKED ISSUE #4638: Bug about "INTERNAL-IP" messages
**What happened**:
When I change the ip of edgecore ,the cloud message("INTERNAL-IP" ) is not right.When I `kubetcl get node -owide`
**What you expected to happen**:
Maybe it can changes at same time.This still seems to make the state ready, though
**How to reproduce it (as minimally and precisely as possible)**:
From using static addresses to changing dncp

**Anything else we need to know?**:
My edgecore is use VM,maybe it is a problem
**Environment**:
- Kubernetes version (use `kubectl version`):v1.22.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.11.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):centeros7.6
  - Kernel (e.g. `uname -a`):5.19.0-1.el7.elrepo.x86_64
  - Go version (e.g. `go version`):1.17
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):v1.11.1
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7
  - Kernel (e.g. `uname -a`):3.10.0-1160.el7.x86_64
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

drop nodeIP initialization in edged.  NodeIP initialization can be completed in `nodestatus/setters` in Kubelet.

Also Kubelet can get nodeIP periodically and report it to cloud when nodeIP is not setted in `edgecore.yaml`. 

**Which issue(s) this PR fixes**:

Fixes #4638

### CODE REVIEW

File: edge/cmd/edgecore/app/server.go [hunk 1]
```diff
@@ -125,21 +124,6 @@ offering HTTP client capabilities to components of cloud to reach HTTP servers r
 				}
 				config.Modules.Edged.NodeIP = ip.String()
 				klog.Infof("Get IP address by custom interface successfully, %s: %s", config.Modules.Edged.CustomInterfaceName, config.Modules.Edged.NodeIP)
-			} else {
```
Comment (wackxu) [inline edge/cmd/edgecore/app/server.go:128]: edgestream is use the nodeIP to register the session to the cloudstream, if we just delete the code, the stream may have some probleam
```
header.Add(stream.SessionKeyInternalIP, e.nodeIP)
```
	internalIP := r.HeaderParameter(stream.SessionKeyInternalIP)
	if internalIP == "" {
		internalIP = strings.Split(r.Request.RemoteAddr, ":")[0]
	}
```

```

File: pkg/apis/componentconfig/edgecore/v1alpha2/default.go [hunk 2]
```diff
@@ -54,7 +54,6 @@ func NewDefaultEdgeCoreConfig() *EdgeCoreConfig {
 				TailoredKubeletConfig: &defaultTailedKubeletConfig,
 				TailoredKubeletFlag: TailoredKubeletFlag{
 					HostnameOverride: hostnameOverride,
-					NodeIP:           localIP,
```
Comment (fisherxu) [inline pkg/apis/componentconfig/edgecore/v1alpha2/default.go:57]: Also checked, If the `NodeIP` is set, the kubelet‘s setter status will not get by `hostnameOverride`.

File: edge/pkg/edgestream/edgestream.go [hunk 3]
```diff
@@ -42,18 +44,33 @@ type edgestream struct {
...
+	var err error
+	if nodeIP == "" {
+		nodeIP, err = util.GetLocalIP(util.GetHostname())
+		if err != nil {
+			klog.Errorf("Failed to get Local IP address: %v", err)
+			return nil, err
+		}
+		klog.Infof("Get node local IP address successfully: %s", nodeIP)
+	}
+
```
Comment (fisherxu) [inline edge/pkg/edgestream/edgestream.go:57]: We can open an issue to track, whether it's need to detect and update the nodeIP periodly in all models which use the nodeIP

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve
