### PR TITLE
keadm: fix get version issue

### LINKED ISSUE #1629: Failed to get the latest KubeEdge release version
When do not specify kubeedge version, keadm can not get latest version:
```
# ./_output/local/bin/keadm init
Failed to get the latest KubeEdge release version, will use default version 
...
```

### PR DESCRIPTION
**Pull request by daixiang0**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1629

### CODE REVIEW

File: keadm/cmd/keadm/app/cmd/cloud/init.go [hunk 1]
```diff
@@ -112,12 +112,13 @@ func Add2ToolsList(toolList map[string]types.ToolsInstaller, flagData map[string
 	if kubeVer == "" {
 		var latestVersion string
 		for i := 0; i < util.RetryTimes; i++ {
```
Comment (kevin-wangzefeng) [inline keadm/cmd/keadm/app/cmd/cloud/init.go:114]: The for loop is useless here, since any error will make return the function.

File: keadm/cmd/keadm/app/cmd/cloud/init.go [hunk 2]
```diff
@@ -112,12 +112,13 @@ func Add2ToolsList(toolList map[string]types.ToolsInstaller, flagData map[string
...
-			latestVersion, err := util.GetLatestVersion()
+			version, err := util.GetLatestVersion()
 			if err != nil {
 				return err
 			}
-			if len(latestVersion) != 0 {
```
Comment (RainbowMango) [inline keadm/cmd/keadm/app/cmd/cloud/init.go:119]: Personaly, I like `len(latestVersion) > 0` better than `len(latestVersion) != 0`

File: keadm/cmd/keadm/app/cmd/cloud/init.go [hunk 3]
```diff
@@ -112,12 +112,13 @@ func Add2ToolsList(toolList map[string]types.ToolsInstaller, flagData map[string
 	if kubeVer == "" {
 		var latestVersion string
 		for i := 0; i < util.RetryTimes; i++ {
-			latestVersion, err := util.GetLatestVersion()
```
Comment (RainbowMango) [inline keadm/cmd/keadm/app/cmd/cloud/init.go:115]: nice catch!

File: keadm/cmd/keadm/app/cmd/cloud/init.go (hunk 1 above)
Comment (daixiang0) [reply keadm/cmd/keadm/app/cmd/cloud/init.go:114]: I think this for loop is for retry setting, any error make it return is what we want.

File: keadm/cmd/keadm/app/cmd/cloud/init.go [hunk 4]
```diff
@@ -112,12 +112,13 @@ func Add2ToolsList(toolList map[string]types.ToolsInstaller, flagData map[string
...
+			version, err := util.GetLatestVersion()
 			if err != nil {
 				return err
 			}
-			if len(latestVersion) != 0 {
-				kubeVer = latestVersion[1:]
+			if len(version) > 0 {
+				kubeVer = version[1:]
```
Comment (kevin-wangzefeng) [inline keadm/cmd/keadm/app/cmd/cloud/init.go:120]: use [strings.TrimPrefix()](https://golang.org/pkg/strings/#TrimPrefix) here to improve readability?

```suggestion
				strings.TrimPrefix(kubeVer, "v")
```

Comment (daixiang0) [reply keadm/cmd/keadm/app/cmd/cloud/init.go:120]: It would be better!
