### PR TITLE
fix: manual PR in reference to 6366 for release 1.20 : convCRI

### LINKED ISSUE #6308: keadm join with --image-repository always failed
**What happened**:
When using the keadm join command with the --image-repository parameter, the image pull may fail

**What you expected to happen**:
keadm should pull image from --image-repository

**How to reproduce it (as minimally and precisely as possible)**:
keadm join \
        --cloudcore-ipport=10.211.55.96:10000 \
        --kubeedge-version=1.18.0 \
	--image-repository=nexus:8082 \
        --edgenode-name=edge-1\
        --cgroupdriver=systemd \
        --remote-runtime-endpoint=unix:///var/run/containerd/containerd.sock \
        --token=some-token

I0506 22:10:24.497409    2396 command.go:925] 1. Check KubeEdge edgecore process status
I0506 22:10:24.502674    2396 command.go:925] 2. Check if the management directory is clean
I0506 22:10:24.502736    2396 join.go:94] 3. Create the necessary directories
I0506 22:10:24.506560    2396 join_others.go:193] 4. Pull Images
Pulling nexus:8082/installation-package:v1.18.0 ...
E0506 22:10:24.507368    2396 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to parse image reference \"docker.io/nexus:8082/installation-package:v1.18.0\": invalid reference format" image="docker.io/nexus:8082/installation-package:v1.18.0"
Error: edge node join failed: pull Images failed: failed to parse image reference "docker.io/nexus:8082/installation-package:v1.18.0": invalid reference format
execute keadm command failed:  edge node join failed: pull Images failed: failed to parse image reference "docker.io/nexus:8082/installation-package:v1.18.0": invalid reference format

**Anything else we need to know?**:
I can pull image from my private repository through ctr pull command.

ctr -n k8s.io images pull --plain-http=true nexus:8082/installation-package:v1.18.0
nexus:8082/installation-package:v1.18.0:                                          resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:c747a31f1ee623e494204f85ffcb63996230e96f1df7118cc7ae64550f173c8e:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:601732011d3f836f77282a1c1d875a119c9fe23df9870a1ebab55a4c1065be2a: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:f3bafe4a3d5551ab38f9cf42290fb5ce6fc5b8f62e94ac1c8a1fe3a2763ac836:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:7f8ef08e85adb2e0a8e170480033b585598619a5675768da9972914138e520de:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:793d1bf6879a12a6d70ab41a881337cbd74cdf20be4c3ea41147df7d74d93473:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:d4df5fff14b79ba5c5481d7b6823e7e9a5d4b41b3ed60f03989408b7468d069e:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:2ce042f597e2f027fa881a2130aaa89bf10e74bd57e3244d04ddde7ec481312a:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)
unpacking linux/arm64/v8 sha256:c747a31f1ee623e494204f85ffcb63996230e96f1df7118cc7ae64550f173c8e...
done: 5.004833ms

I can also deploy cloudcore on cloud node with keadm init --image-repository=nexus:8082

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28.13
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.18.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): ubuntu/24.04
  - Kernel (e.g. `uname -a`): 6.8.0-51-generic
  - Go version (e.g. `go version`): 
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  PRETTY_NAME="Ubuntu 24.04.1 LTS"
  NAME="Ubuntu"
  VERSION_ID="24.04"
  VERSION="24.04.1 LTS (Noble Numbat)"
  VERSION_CODENAME=noble
  ID=ubuntu
  ID_LIKE=debian
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  UBUNTU_CODENAME=noble
  LOGO=ubuntu-logo
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by Spiral-Memory**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:
Replaces the custom logic in `ConvToCRIImage()` function with `reference.ParseAnyReference()` from the `github.com/distribution/reference` package. This ensures standards-compliant image reference parsing and improves maintainability.

**Which issue(s) this PR fixes**:
Fixes #6308 

**Special notes for your reviewer**:
Please confirm that replacing the basic logic in `ConvToCRIImage()` is acceptable across all image-handling cases. Your review is appreciated.

Below are screenshots after making the change. I added some print statements to log the formed reference:

* **Default (without `--image-repository` flag):**
  Screenshot from 2025-06-24 10-11-22

* **With `--image-repository` flag (shows it forms the reference correctly):**
  Screenshot from 2025-06-24 10-11-37

**Does this PR introduce a user-facing change?**:
```release-note
Removed internal logic in ConvToCRIImage function and now use reference.ParseAnyReference to handle image parsing more reliably.

### CODE REVIEW

File: keadm/cmd/keadm/app/cmd/util/image_test.go [hunk 1]
```diff
@@ -0,0 +1,108 @@
+package util
```
Comment (Shelley-BaoYue) [inline keadm/cmd/keadm/app/cmd/util/image_test.go:17]: Please add a copyright for new file.

Comment (Spiral-Memory) [reply keadm/cmd/keadm/app/cmd/util/image_test.go:17]: Added
