### PR TITLE
fix reDownload serviceFile

### LINKED ISSUE #2162: Discussion: Support cloudcore to run as system service
**What would you like to be added/modified**:
Support CloudCore run as service :

- [x] fix some bugs of run edgecore as systemd service

- [ ] support cloudcore run as systemd service

- [ ] add option to keadm, for users to indicated whether cloudcore to be installed as a system service or deployment in K8s

- [ ] update document of [keadm.setup](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/keadm.md)

**releated issues**
#2142
**Why is this needed**:
According to @luogangyi 

> I think running cloudcore in containers is easy to achieve high availability while running in systemd is easy to configure and test. They are not conflict.

For me, it support a easy way to restart cloudcore.

### LINKED ISSUE #2183: edgecore service fail to download when keadm setup edgecore, should skip download when it exists
**What would you like to be added/modified**:
Skip the service fail to download when keadm setup edgecore.

Should skip the download from internet when it exists
**Why is this needed**:
Or it will always fail when network problem..

### PR DESCRIPTION
**Pull request by GsssC**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Now keadm join use `wget` and cause reDownload as below:
image

**Which issue(s) this PR fixes**:

part of #2162
fix #2183

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 1]
```diff
@@ -386,31 +386,34 @@ func installKubeEdge(componentType types.ComponentType, arch string, version sem
...
-		strippedVersion := fmt.Sprintf("%d.%d", version.Major, version.Minor)
-
-		//	No need to download if the version is less than 1.1 (or 1.1.0)
-		if version.GE(semver.MustParse("1.1.0")) {
-			try := 0
-
-			edgecoreServiceFileName := "edgecore.service"
+	strippedVersion := fmt.Sprintf("%d.%d", version.Major, version.Minor)
 
+	//	No need to download if the version is less than 1.1 (or 1.1.0)
```
Comment (daixiang0) [inline keadm/cmd/keadm/app/cmd/util/common.go:391]: Notice the blank.

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 2]
```diff
@@ -386,31 +386,34 @@ func installKubeEdge(componentType types.ComponentType, arch string, version sem
...
+	if hasSystemd() && version.GE(semver.MustParse("1.1.0")) {
+		var urlForServiceFile string
+		var ServiceFileName string
+		if componentType == types.EdgeCore {
+			ServiceFileName = "edgecore.service"
 			if version.EQ(semver.MustParse("1.1.0")) {
-				edgecoreServiceFileName = "edge.service"
+				ServiceFileName = "edge.service"
```
Comment (daixiang0) [inline keadm/cmd/keadm/app/cmd/util/common.go:398]: Unit as `edgecore.service` is better.

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 3]
```diff
@@ -386,31 +386,34 @@ func installKubeEdge(componentType types.ComponentType, arch string, version sem
...
 				}
-				break
-			}
-			if try == downloadRetryTimes {
-				return fmt.Errorf("failed to download %s", edgecoreServiceFileName)
+			} else {
+				return err
 			}
+		} else {
+			fmt.Printf("[Run as service]serviceFile already exisits in %s, skip download\n", ServiceFilePath)
```
Comment (daixiang0) [inline keadm/cmd/keadm/app/cmd/util/common.go:416]: Not use camel case word, better to outpur as below:
```
service file already exists as %s, skip download
```

File: keadm/cmd/keadm/app/cmd/util/common.go (hunk 2 above)
Comment (GsssC) [reply keadm/cmd/keadm/app/cmd/util/common.go:398]: It is a history question, in version v1.1.0, service file name called `edge.service` as https://github.com/kubeedge/kubeedge/blob/release-1.1/build/tools/edge.service

Comment (daixiang0) [reply keadm/cmd/keadm/app/cmd/util/common.go:398]: Get.

**Comment by luogangyi** [comment]
lgtm

**Comment by kevin-wangzefeng** [comment]
@GsssC can you add tests for this? Better to be e2e, but ut is also fine.

**Comment by GsssC** [comment]
@kevin-wangzefeng 
well :)

**Comment by kevin-wangzefeng** [comment]
Let me know when this PR is ready for another round of review

**Comment by GsssC** [comment]
@kevin-wangzefeng I am working on adding test now . : )

**Comment by GsssC** [comment]
@kevin-wangzefeng 
@fisherxu 
@daixiang0 
all is ready!PTAL :)

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 4]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
 		return false, fmt.Errorf("Invalid Input")
 	}
 }
+
+func downloadServiceFile(componentType types.ComponentType, version semver.Version, storeDir string) error {
+	//No need to download if
```
Comment (daixiang0) [inline keadm/cmd/keadm/app/cmd/util/common.go:655]: Add blank after "//"

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 5]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
...
+		case types.EdgeCore:
+			ServiceFileName = EdgeServiceFile
+			if version.EQ(semver.MustParse("1.1.0")) {
+				ServiceFileName = OldEdgeServiceFile
+			}
+		default:
+			return fmt.Errorf("component type %s not support", componentType)
+		}
+		ServiceFilePath := storeDir + "/" + ServiceFileName
+		strippedVersion := fmt.Sprintf("%d.%d", version.Major, version.Minor)
```
Comment (daixiang0) [inline keadm/cmd/keadm/app/cmd/util/common.go:677]: remove tmp val

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 6]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
...
+		ServiceFileURL := fmt.Sprintf(ServiceFileURLFormat, strippedVersion, ServiceFileName)
+		if _, err := os.Stat(ServiceFilePath); err != nil {
+			if os.IsNotExist(err) {
+				cmdStr := fmt.Sprintf("cd %s && sudo -E wget -t %d -k --no-check-certificate %s", storeDir, RetryTimes, ServiceFileURL)
+				fmt.Printf("[Run as service]start to download service file for %s\n", componentType)
```
Comment (daixiang0) [inline keadm/cmd/keadm/app/cmd/util/common.go:682]: Add blank after "]"

File: keadm/cmd/keadm/app/cmd/util/common.go (hunk 5 above)
Comment (GsssC) [reply keadm/cmd/keadm/app/cmd/util/common.go:677]: sorry, what does "temp val" mean here?

Comment (daixiang0) [reply keadm/cmd/keadm/app/cmd/util/common.go:677]: strippedVersion.

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 7]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
...
+			ServiceFileName = EdgeServiceFile
+			if version.EQ(semver.MustParse("1.1.0")) {
+				ServiceFileName = OldEdgeServiceFile
+			}
+		default:
+			return fmt.Errorf("component type %s not support", componentType)
+		}
+		ServiceFilePath := storeDir + "/" + ServiceFileName
+		strippedVersion := fmt.Sprintf("%d.%d", version.Major, version.Minor)
+		ServiceFileURL := fmt.Sprintf(ServiceFileURLFormat, strippedVersion, ServiceFileName)
```
Comment (GsssC) [inline keadm/cmd/keadm/app/cmd/util/common.go:678]: @daixiang0 is it?
```suggestion
        ServiceFileURL := fmt.Sprintf(ServiceFileURLFormat, fmt.Sprintf("%d.%d", version.Major, version.Minor), ServiceFileName)
```

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 8]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
 		return false, fmt.Errorf("Invalid Input")
 	}
 }
+
+func downloadServiceFile(componentType types.ComponentType, version semver.Version, storeDir string) error {
+	//No need to download if
+	//1. the systemd not exists
+	//2. the version is less than 1.1.0
+	//3. the service file already exists
```
Comment (GsssC) [inline keadm/cmd/keadm/app/cmd/util/common.go:658]:
```suggestion
	// No need to download if
	// 1. the systemd not exists
	// 2. the version is less than 1.1.0
	// 3. the service file already exists
```

File: keadm/cmd/keadm/app/cmd/util/common.go (hunk 6 above)
Comment (GsssC) [inline keadm/cmd/keadm/app/cmd/util/common.go:682]:
```suggestion
				fmt.Printf("[Run as service] start to download service file for %s\n", componentType)
```

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 9]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
...
+		strippedVersion := fmt.Sprintf("%d.%d", version.Major, version.Minor)
+		ServiceFileURL := fmt.Sprintf(ServiceFileURLFormat, strippedVersion, ServiceFileName)
+		if _, err := os.Stat(ServiceFilePath); err != nil {
+			if os.IsNotExist(err) {
+				cmdStr := fmt.Sprintf("cd %s && sudo -E wget -t %d -k --no-check-certificate %s", storeDir, RetryTimes, ServiceFileURL)
+				fmt.Printf("[Run as service]start to download service file for %s\n", componentType)
+				if _, err := runCommandWithStdout(cmdStr); err != nil {
+					return err
+				}
+				fmt.Printf("[Run as service]success to download service file for %s\n", componentType)
```
Comment (GsssC) [inline keadm/cmd/keadm/app/cmd/util/common.go:686]:
```suggestion
				fmt.Printf("[Run as service] success to download service file for %s\n", componentType)
```

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 10]
```diff
@@ -675,3 +650,46 @@ func askForconfirm() (bool, error) {
...
+			} else {
+				return err
+			}
+		} else {
+			fmt.Printf("[Run as service]service file already exisits in %s, skip download\n", ServiceFilePath)
```
Comment (GsssC) [inline keadm/cmd/keadm/app/cmd/util/common.go:691]:
```suggestion
			fmt.Printf("[Run as service] service file already exisits in %s, skip download\n", ServiceFilePath)
```

File: keadm/cmd/keadm/app/cmd/util/common.go (hunk 7 above)
Comment (daixiang0) [reply keadm/cmd/keadm/app/cmd/util/common.go:678]: Use one `fmt.Sprintf` is enough.

File: keadm/cmd/keadm/app/cmd/util/common.go (hunk 5 above)
Comment (GsssC) [reply keadm/cmd/keadm/app/cmd/util/common.go:677]: But I still think this temp variable is needed, or line about constructing serviceFileURL would be very long. 
: )

**Comment by fisherxu** [comment]
@GsssC The CI is failed

**Comment by GsssC** [comment]
@fisherxu it is ok now.

File: keadm/cmd/keadm/app/cmd/util/common.go [hunk 11]
```diff
@@ -867,3 +842,46 @@ func IsProcessRunningWithFilter(proc string, filter string) (bool, error) {
...
+		switch componentType {
+		case types.CloudCore:
+			ServiceFileName = CloudServiceFile
+			if version.EQ(semver.MustParse("1.1.0")) {
+				fmt.Println("[Run as service]skip download service file for cloudcore-v1.1.0, not support")
+				return nil
+			}
+		case types.EdgeCore:
+			ServiceFileName = EdgeServiceFile
+			if version.EQ(semver.MustParse("0.1.0")) {
```
Comment (GsssC) [inline keadm/cmd/keadm/app/cmd/util/common.go:862]:
```suggestion
			if version.EQ(semver.MustParse("1.1.0")) {
```

**Comment by GsssC** [comment]
wait for squash if ci success

**Comment by GsssC** [comment]
@fisherxu it is ok now.

**Comment by daixiang0** [comment]
Fix #2307

File: keadm/cmd/keadm/app/cmd/util/common_test.go [hunk 12]
```diff
@@ -70,3 +81,139 @@ func TestManagedKubernetesVersion(t *testing.T) {
...
+			if err == nil {
+				err = errors.New("nil")
+			}
+			t.Fatalf("check should return error{%s} but not,error:{%s}\n", os.ErrNotExist, err.Error())
+		}
+		clean(testTmpDir)
+	})
+
+	componentType = types.CloudCore
+	targetVersion, _ = semver.Make(types.LatestKubeEdgeVersion)
```
Comment (fisherxu) [inline keadm/cmd/keadm/app/cmd/util/common_test.go:154]: Please use the `DefaultKubeEdgeVersion` here, no need create a new one, `DefaultKubeEdgeVersion` is the latest one.

Comment (GsssC) [reply keadm/cmd/keadm/app/cmd/util/common_test.go]: Done : )

**Comment by fisherxu** [comment]
/lgtm
/approve
Pick this pr to release-1.5 :)
