### PR TITLE
Mismatch in access mode names

### LINKED ISSUE #545: Action not performing as expected in Bluetooth Mapper
**What happened**:
While using bluetooth mapper with CC2650-sensortag , it is observed that the Action Manager is not performing action as specified in the config file. 

**What you expected to happen**:
It is expected to perform action as specified in the config file. 

**How to reproduce it (as minimally and precisely as possible)**:
Run bluetooth mapper and test using CC3650-SensorTag

**Anything else we need to know?**:
It was observed that the struct "Action" was not getting proper values upon running the mapper.

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
This PR fixes a mismatch in the Access mode names due to which the action manager is not performing as expected in the bluetooth mapper

**Which issue(s) this PR fixes**:
Fixes #545

### CODE REVIEW

File: device/bluetooth_mapper/configuration/config.go [hunk 1]
```diff
@@ -182,7 +184,7 @@ func (b *BLEConfig) Load() error {
 			if strings.ToUpper(deviceModel.Name) == strings.ToUpper(b.Device.Name) {
 				for _, property := range deviceModel.Properties {
 					if strings.ToUpper(property.Name) == strings.ToUpper(actionConfig.PropertyName) {
-						if strings.ToUpper(property.AccessMode) == "RW" {
+						if strings.ToUpper(property.AccessMode) == strings.ToUpper(READWRITE){
```
Comment (rohitsardesai83) [inline device/bluetooth_mapper/configuration/config.go]: can't we just compare without comparing to upper case ? since our schema is defined , users are expected to provide the correct enum values.

Comment (sujithsimon22) [reply device/bluetooth_mapper/configuration/config.go]: Removed case insensitive check and replaced it with a case sensitive one. Going forward when we have API validation we can prevent the users from accidentally giving the wrong case for enum values, thus eliminating the need for a case insensitive check. Thanks

**Comment by sujithsimon22** [comment]
cc @m1093782566

**Comment by m1093782566** [comment]
Let's get it in.

/approve
