### PR TITLE
remove pid namespace config in copy-resource

### LINKED ISSUE #5139: Keadm join is not working when using CRI-O as container runtime
**What happened**:
I'm trying to join a Kubeedge edge node which uses _CRI-O v1.24.6_ as the container runtime, but it shows an error in the installation step number 5 (5. Copy resources from the image to the management directory). This installation error is not produced if I use _containerd_ as the container runtime.

The command I used to join the edge node:
`keadm join --cloudcore-ipport=192.168.250.208:10000 --token=<kubeedge-token> --kubeedge-version=v1.15.0 --cgroupdriver=systemd --runtimetype=remote --remote-runtime-endpoint=unix:///var/run/crio/crio.sock `

The output of the command:

`I1103 11:23:56.366048   4610 command.go:901] 1. Check KubeEdge edgecore process status`
`I1103 11:23:56.373433    4610 command.go:901] 2. Check if the management directory is clean`
`I1103 11:23:56.373686    4610 join.go:107] 3. Create the necessary directories`
`I1103 11:23:56.379396    4610 join.go:184] 4. Pull Images`
`Pulling docker.io/kubeedge/installation-package:v1.15.0 ...`
`Successfully pulled docker.io/kubeedge/installation-package:v1.15.0`
`Pulling docker.io/library/eclipse-mosquitto:1.6.15 ...`
`Successfully pulled docker.io/library/eclipse-mosquitto:1.6.15`
`Pulling docker.io/kubeedge/pause:3.6 ...`
`Successfully pulled docker.io/kubeedge/pause:3.6`
`I1103 11:23:56.387827    4610 join.go:184] 5. Copy resources from the image to the management directory`
`E1103 11:23:56.504779    4610 remote_runtime.go:302] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Unknown desc = Pod level PID namespace requested for the container, but pod sandbox was not similarly configured, and does not have an infra container" podSandboxID="47f4560f902d452ef0b39995528b95fec923f65440279eee01742f75b2334467"
Error: edge node join failed: copy resources failed: create container failed: rpc error: code = Unknown desc = Pod level PID namespace requested for the container, but pod sandbox was not similarly configured, and does not have an infra container
execute keadm command failed:  edge node join failed: copy resources failed: create container failed: rpc error: code = Unknown desc = Pod level PID namespace requested for the container, but pod sandbox was not similarly configured, and does not have an infra container`

**What you expected to happen**:

Run the _keadm join_ command in an edge node to install Kubeedge v1.15.0 and join this node to a Kubeedge cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Run in an edge node this command:
`keadm join --cloudcore-ipport=192.168.250.208:10000 --token=<kubeedge-token> --kubeedge-version=v1.15.0 --cgroupdriver=systemd --runtimetype=remote --remote-runtime-endpoint=unix:///var/run/crio/crio.sock `

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24.17
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.15.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`): Ubuntu 22.04.3 LTS
  - Kernel (e.g. `uname -a`): 5.15.0-88-generic
  - Container runtime: containerd v1.6.24

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):  v1.15.0
  - OS (e.g. `cat /etc/os-release`): Ubuntu 22.04.3 LTS
  - Kernel (e.g. `uname -a`): 5.15.0-88-generic
  - Container runtime: CRI-O v1.24.6

  </details>

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Remove pid namespace config for it is unnecessary. But we still need to config network namespace config, otherwise we will join edgecore failed with the error as below

image

**Which issue(s) this PR fixes**:

Fixes #5139

### CODE REVIEW

File: keadm/cmd/keadm/app/cmd/util/image.go [hunk 1]
```diff
@@ -281,8 +281,6 @@ func (runtime *CRIRuntime) CopyResources(edgeImage string, files map[string]stri
 			SecurityContext: &runtimeapi.LinuxSandboxSecurityContext{
 				NamespaceOptions: &runtimeapi.NamespaceOption{
 					Network: runtimeapi.NamespaceMode_POD,
-					Pid:     runtimeapi.NamespaceMode_CONTAINER,
-					Ipc:     runtimeapi.NamespaceMode_POD,
```
Comment (fisherxu) [inline keadm/cmd/keadm/app/cmd/util/image.go:285]: Plz give more discriptions for why delete `pid` and `ipc` above :)

**Comment by fisherxu** [comment]
> I am wondering if we can add more test cases for different runtimes. @fisherxu @WillardHu @zhiyingfang2022 @wlq1212

+1 We can add tests for different runtime like `containerd` `cri-o`, etc.

**Comment by Shelley-BaoYue** [comment]
> > I am wondering if we can add more test cases for different runtimes. @fisherxu @WillardHu @zhiyingfang2022 @wlq1212
> 
> +1 We can add tests for different runtime like `containerd` `cri-o`, etc.

File: keadm/cmd/keadm/app/cmd/util/image.go (hunk 1 above)
Comment (Shelley-BaoYue) [reply keadm/cmd/keadm/app/cmd/util/image.go:285]: > Plz give more discriptions for why delete `pid` and `ipc` above :)

Using the default value for Pid and Ipc is enough for copy-resource container. If we set Pid with NamespaceMode_CONTAINER, keadm join with cri-o runtime will fail to create copy-resource container like #5139

**Comment by Shelley-BaoYue** [comment]
> > I am wondering if we can add more test cases for different runtimes. @fisherxu @WillardHu @zhiyingfang2022 @wlq1212
> 
> +1 We can add tests for different runtime like `containerd` `cri-o`, etc.

I have created an issue #5182 to track.

File: keadm/cmd/keadm/app/cmd/util/image.go (hunk 1 above)
Comment (fisherxu) [reply keadm/cmd/keadm/app/cmd/util/image.go:285]: Okey, sounds good, but the `Pid` and `Ipc` above all use the same default values with k8s, not sure what's the difference with k8s.. cc @Shelley-BaoYue @WillardHu

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by fisherxu** [comment]
Should be picked to release-1.15?

**Comment by Shelley-BaoYue** [comment]
> Should be picked to release-1.15?

yes, I will pick it to release 1.15 and 1.14.
