### PR TITLE
Resolve compilation errors

### LINKED ISSUE #6400: Compilation error in master branch
**What happened**:

Compilation error in master branch

**What you expected to happen**:

No compilation errors

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6400

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by WillardHu** [comment]
PTAL @Shelley-BaoYue @wbc6080

File: cloud/pkg/dynamiccontroller/filter/endpointresource/endpointresource_test.go.bak [hunk 1]
```diff
@@ -216,6 +216,7 @@ func TestFilterEndpointSlice(t *testing.T) {
 }
 
 func TestFilterEndpoints(t *testing.T) {
+	// TODO: Replace with fake client
 	patches := setupPatches()
 	defer patches.Reset()
```
Comment (wbc6080) [inline cloud/pkg/dynamiccontroller/filter/endpointresource/endpointresource_test.go.bak]: It is not common to merge a bak file. If there is a problem with the original test case, I suggest commenting out the relevant test code first and correcting it in the subsequent PR.

Comment (WillardHu) [reply cloud/pkg/dynamiccontroller/filter/endpointresource/endpointresource_test.go.bak]: Done

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve
