### PR TITLE
It test to fix the issue related to random failures

### LINKED ISSUE #231: Fix integration tests with random failures
**Which jobs are failing**:
integration-test

**Which test(s) are failing**:
device tests

**Since when has it been failing**:
Random failures

**Reason for failure**:
device isn't in the context before publish messages to change the state are posted.

**Anything else we need to know**:
Log : 
```sh
------------------------------
• Failure [60.002 seconds]
Event Bus Testing
/home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:36
  Publish on eventbus topics throgh MQTT internal broker
  /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:40
    TC_TEST_EBUS_6: change the device status to online from eventbus [It]
    /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:103
    Timed out after 60.000s.
    Device state is not online within specified time
    Expected
        <string>: unknown
    to equal
        <string>: online
    /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:121
------------------------------
I0313 01:16:08.267387   11721 log.go:70] client.Publish Success !!
I0313 01:16:08.268051   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:08.268186   11721 log.go:70] TestCase:TC_TEST_EBUS_7: change the device status to unknown from eventbus     Status=PASSED
•I0313 01:16:08.269487   11721 log.go:70] client.Publish Success !!
I0313 01:16:08.288640   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:10.289727   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:12.290537   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:14.291630   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:16.292584   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:18.293373   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:20.294272   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:22.295125   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:24.296841   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:26.297880   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:28.298822   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:30.299599   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:32.300341   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:34.301235   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:36.302201   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:38.303965   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:40.304904   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:42.305817   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:44.306685   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:46.307537   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:48.308423   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:50.309306   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:52.310121   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:54.310985   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:56.311882   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:16:58.312780   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:17:00.313650   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:17:02.314514   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:17:04.316847   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:17:06.317866   11721 log.go:65] DeviceID= kubeedge-device-8tmyeg6gdp, DeviceState= unknown
I0313 01:17:08.270440   11721 log.go:70] TestCase:TC_TEST_EBUS_8: change the device status to offline from eventbus     Status=FAILED
------------------------------
• Failure [60.002 seconds]
Event Bus Testing
/home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:36
  Publish on eventbus topics throgh MQTT internal broker
  /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:40
    TC_TEST_EBUS_8: change the device status to offline from eventbus [It]
    /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:147
    Timed out after 60.000s.
    Device state is not offline within specified time
    Expected
        <string>: unknown
    to equal
        <string>: offline
    /home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:164
------------------------------
I0313 01:17:08.270569   11721 log.go:65] Remove Mock device from edgenode !!
I0313 01:17:08.272272   11721 log.go:70] DELETE http://127.0.0.1:12345/devices 200 OK in 1.64897ms
Summarizing 2 Failures:
[Fail] Event Bus Testing Publish on eventbus topics throgh MQTT internal broker [It] TC_TEST_EBUS_6: change the device status to online from eventbus 
/home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:121
[Fail] Event Bus Testing Publish on eventbus topics throgh MQTT internal broker [It] TC_TEST_EBUS_8: change the device status to offline from eventbus 
/home/travis/gopath/src/github.com/kubeedge/kubeedge/edge/test/integration/device/device_test.go:164
Ran 8 of 8 Specs in 120.018 seconds
FAIL! -- 6 Passed | 2 Failed | 0 Pending | 0 Skipped
--- FAIL: TestEdgecoreEventBus (120.02s)
FAIL
```
Failed job URL : https://travis-ci.org/kubeedge/kubeedge/jobs/505530549

### PR DESCRIPTION
**Pull request by srivatsav123**
These changes fixes the issue #231 related to random failures

**What type of PR is this?**

 /kind test

**What this PR does / why we need it**:
IT code changes to fix random failures.
**Which issue(s) this PR fixes**:

Fixes #231 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by m1093782566** [comment]
@srivatsav123 

I want to know the root cause and why this PR can fix the random failure?

**Comment by srivatsav123** [comment]
@m1093782566 -Please refer to the issue for further details
issue - https://github.com/kubeedge/kubeedge/issues/231

**Cause for random failure**: Since the Devicestate of the device was queried through DB...It takes some amount of time to add the mock device to the context,membership module and then to the DB..Since the publish to the topic was happening first before the fake device added to the DB...Not all time but some times PR was failing(/retest will solve it)..
**Solution**:So permanent solution which i opted was rather than to query through DB..I subscribed to the MQTT topic which device module was publishing..And unmarshalled the message into struct variable, what i needed for the test.

**Comment by m1093782566** [comment]
OK

**Comment by sids-b** [comment]
@srivatsav123 I dont think this will solve the issue. 

> @m1093782566 -Please refer to the issue for further details
> issue - #231
> 
> **Cause for random failure**: Since the Devicestate of the device was queried through DB...It takes some amount of time to add the mock device to the context,membership module and then to the DB..Since the publish to the topic was happening first before the fake device added to the DB...Not all time but some times PR was failing(/retest will solve it)..
I don't think this is the correct solution. In the test case we were waiting for 60 sec for the state to change in the DB.  So i guess 60 secs were more than enough to add a device in a DB.
> **Solution**:So permanent solution which i opted was rather than to query through DB..I subscribed to the MQTT topic which device module was publishing..And unmarshalled the message into struct variable, what i needed for the test.

@srivatsav123 by looking at issue #231 , it is seen that state of the device is unknown whereas it is supposed to be online which means there is some issue in changing the state and not saving in DB

**Comment by srivatsav123** [comment]
Issue
@sids-b -we reproduced the issue ..the problem is  clear in edge  logs which is attached above, that since the publish message is happened first from testcase....Then the device is getting added to the context,membership module that time device will update with unknown state...since we are querying the DB at that time and the time period(60 sec expires)we are getting unknown..

solution :As discussed we have to check whether device is added first, query the added fake device from event bus then do a publish message on the device state topic....

**Comment by sids-b** [comment]
> Issue
> @sids-b -we reproduced the issue ..the problem is clear in edge logs which is attached above, that since the publish message is happened first from testcase....Then the device is getting added to the context,membership module that time device will update with unknown state...since we are querying the DB at that time and the time period(60 sec expires)we are getting unknown..
> 
> solution :As discussed we have to check whether device is added first, query the added fake device from event bus then do a publish message on the device state topic....

Can there not be a possibility that when you query the fake device .... The device is not added and you dont get the fake device you added ? Similar is the case with changing the state of the device.

**Comment by srivatsav123** [comment]
thats what when i am able to query the fake device only i will publish to that device topic.. For that we have to give correct time frame (how much time required by the device twin module to add device into DB)..So we will give that much time frame obviously we will get the fake device details at that time(So what time frame do you suggest can i give for my testcase for the get device details ?)

File: edge/test/integration/device/device_test.go [hunk 1]
```diff
@@ -31,6 +32,38 @@ import (
 	. "github.com/onsi/gomega"
 )
 
+//getting Devicestate from subscribed MQTT topic
+var Devicestate string
```
Comment (sids-b) [inline edge/test/integration/device/device_test.go]: Devicestate -> DeviceState

File: edge/test/integration/device/device_test.go [hunk 2]
```diff
@@ -31,6 +32,38 @@ import (
...
+
+//getting Device_state field from subscribed MQTT topic,Unmarshalling into structure variable
+var Device_state Device_Update
```
Comment (sids-b) [inline edge/test/integration/device/device_test.go]: camel case please

File: edge/test/integration/device/device_test.go [hunk 3]
```diff
@@ -31,6 +32,38 @@ import (
...
+
+type Device_Update struct {
```
Comment (sids-b) [inline edge/test/integration/device/device_test.go]: camel case please.
Applicable to all similar cases below

Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: ok

File: edge/test/integration/device/device_test.go (hunk 2 above)
Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: ok

File: edge/test/integration/device/device_test.go (hunk 1 above)
Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: ok

File: edge/test/integration/device/device_test.go [hunk 4]
```diff
@@ -31,6 +32,37 @@ import (
...
+	DeviceField `json:"device"`
+}
+type DeviceField struct {
+	Name       string `json:"name"`
+	State      string `json:"state"`
+	LastOnline string `json:"last_online"`
+}
+
+// Mqtt client is subscribed to this topic,for the state update
+func SubMessageReceived(client MQTT.Client, message MQTT.Message) {
```
Comment (rohitsardesai83) [inline edge/test/integration/device/device_test.go]: why are we passing client here ?

Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: SubMessagereceived is a type  of message handler function which receives two paramaeter (client,message.)..Eventhough we have not uses client inside the function defination .We should pass it otherwise compilation fails.

File: edge/test/integration/device/device_test.go [hunk 5]
```diff
@@ -31,6 +32,37 @@ import (
 	. "github.com/onsi/gomega"
 )
 
+//getting Devicestate from subscribed MQTT topic
```
Comment (m1093782566) [inline edge/test/integration/device/device_test.go]: Comment should be started with "Devicestate ..."

File: edge/test/integration/device/device_test.go [hunk 6]
```diff
@@ -31,6 +32,37 @@ import (
...
+var DeviceState string
+
+//getting Device_state field from subscribed MQTT topic,Unmarshalling into structure variable
```
Comment (m1093782566) [inline edge/test/integration/device/device_test.go]: What's the comment for?

File: edge/test/integration/device/device_test.go [hunk 7]
```diff
@@ -31,6 +32,37 @@ import (
...
+	Timestamp   int    `json:"timestamp"`
+	DeviceField `json:"device"`
+}
+type DeviceField struct {
+	Name       string `json:"name"`
+	State      string `json:"state"`
+	LastOnline string `json:"last_online"`
+}
+
+// Mqtt client is subscribed to this topic,for the state update
```
Comment (m1093782566) [inline edge/test/integration/device/device_test.go]: Comment should be started with "SubMessageReceived..."

File: edge/test/integration/device/device_test.go [hunk 8]
```diff
@@ -110,65 +145,85 @@ var _ = Describe("Event Bus Testing", func() {
...
-			if Token_client = Client.Publish(dtcommon.DeviceETPrefix+DeviceIDN+dtcommon.DeviceETStateUpdateSuffix, 0, false, body); Token_client.Wait() && Token_client.Error() != nil {
-				common.Failf("client.Publish() Error is %s", Token_client.Error())
-			} else {
-				common.InfoV6("client.Publish Success !!")
+			Eventually(func() string {
+				Devicedb = GetDeviceFromDB(DeviceIDN)
+				return Devicedb.ID
+			}, "10s", "2s").Should(Equal(DeviceIDN), "Device is queried from database")
+			if strings.Compare(Devicedb.ID, DeviceIDN) == 0 {
+				if Token_client = Client.Publish(dtcommon.DeviceETPrefix+DeviceIDN+dtcommon.DeviceETStateUpdateSuffix, 0, false, body); Token_client.Wait() && Token_client.Error() != nil {
```
Comment (rohitsardesai83) [inline edge/test/integration/device/device_test.go]: follow camelCasing for variable name

File: edge/test/integration/device/device_test.go (hunk 5 above)
Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: ok

File: edge/test/integration/device/device_test.go (hunk 6 above)
Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: not required removed

File: edge/test/integration/device/device_test.go (hunk 8 above)
Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: ok

File: edge/test/integration/device/device_test.go (hunk 7 above)
Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: ok

File: edge/test/integration/device/device_test.go [hunk 9]
```diff
@@ -41,134 +70,156 @@ var DeviceTW dttype.Device
...
 			if err != nil {
 				common.Failf("Marshal failed %v", err)
 			}
-
-			if Token_client = Client.Publish(dtcommon.DeviceETPrefix+DeviceIDN+dtcommon.DeviceETStateUpdateSuffix, 0, false, body); Token_client.Wait() && Token_client.Error() != nil {
-				common.Failf("client.Publish() Error is %s", Token_client.Error())
-			} else {
-				common.InfoV6("client.Publish Success !!")
+			Eventually(func() string {
+				Devicedb = GetDeviceFromDB(DeviceIDN)
```
Comment (sids-b) [inline edge/test/integration/device/device_test.go]: Is it necessary that e directly get the device from DB ? Can we use deviceTwin MQTT API's to get the device ?

Comment (srivatsav123) [reply edge/test/integration/device/device_test.go]: can be done...changed it..
