### PR TITLE
Fix no prompt while executing `make all` without sed

### LINKED ISSUE #3562: No prompt when executing `make all` without sed
**What happened**:

Currently, if we do not have sed installed and execute `make all`, we will get the result below. This is not what we want because `Please install gnu-sed (brew install gnu-sed)` does not show up.

截屏2022-01-18 上午12 24 20

**What you expected to happen**:

echo "Please install gnu-sed (brew install gnu-sed)"

**How to reproduce it (as minimally and precisely as possible)**:

Execute `make all` on machines without gnu-sed/sed installed

**Anything else we need to know?**:

See https://github.com/kubeedge/kubeedge/blob/f0ede113313f718505bd12e0803ce8577975d804/hack/lib/lint.sh#L28

The script exits directly after executing `which gsed`

### PR DESCRIPTION
**Pull request by JooKS-me**
Signed-off-by: zhukunshuai <jookunshuai@gmail.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

If sed/gnu-sed is not installed, it will not exit immediately, but will prompt that it is not installed.

image

**Which issue(s) this PR fixes**:

Fixes #3562

### CODE REVIEW

**Comment by gy95** [comment]
on my local machine, there's one error
```
# make lint
hack/make-rules/lint.sh
checking golangci-lint
found golangci-lint, version: golangci-lint has version 1.42.0 built from c6142e38 on 2021-08-17T11:47:22Z
start lint ...
check any whitenoise ...
xargs: s/[ \t]*$//: No such file or directory
Makefile:124: recipe for target 'lint' failed
make: *** [lint] Error 127
```

**Review by gy95 — COMMENTED** [review]
in line 56 or line 53, variable SED_CMD is not defined if fixing in this way.

**Comment by gy95** [comment]
what's `which gsed` cmd output on your mac os machine. It should  output `Please install gnu-sed (brew install gnu-sed)` if sed is not installed.

**Comment by JooKS-me** [comment]
> in line 56 or line 53, variable SED_CMD is not defined if fixing in this way.

Yep, this is my oversight, I will fix it later.



> what's `which gsed` cmd output on your mac os machine. It should output `Please install gnu-sed (brew install gnu-sed)` if sed is not installed.

It will not output this, but exit the script directly, right?

**Review by fisherxu — COMMENTED** [review]
L23-47 should be wrapped in a function like `kubeedge::lint::init`? `make all` should not check the sed cmd, just because source this script in `init.sh`.

**Comment by JooKS-me** [comment]
> L23-47 should be wrapped in a function like `kubeedge::lint::init`? `make all` should not check the sed cmd, just because source this script in `init.sh`.

Yep, I think so too, and I've done it~

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve
/hold
@gy95 for final review.

File: hack/lib/lint.sh [hunk 1]
```diff
@@ -20,31 +20,36 @@ set -o errexit
...
+    if [[ "$OSTYPE" == "darwin"* ]]
     then
-        echo "Please install gnu-sed (brew install gnu-sed)"
-        exit 1
-    fi
-elif [[ "$OSTYPE" == "linux"* ]]
-then
-    SED_CMD=`which sed`
-    if [ -z $SED_CMD ]
+        if ! which gsed >/dev/null 2>&1
```
Comment (gy95) [inline hack/lib/lint.sh:29]: I don't think this is necessary. IMHO, these two are equal :)
```
SED_CMD=`which gsed`
    if [ -z $SED_CMD ]
```
`if ! which gsed >/dev/null 2>&1`

What is the output of  `which gsed` or `make lint` cmd if gsed is not installed?

Comment (fisherxu) [reply hack/lib/lint.sh:29]: you can try it in your linux host, modify the sed to as `sedddd`, seems needed.

File: hack/lib/lint.sh [hunk 2]
```diff
@@ -20,31 +20,36 @@ set -o errexit
...
 
-SED_CMD=""
-KUBEEDGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
+function kubeedge::lint::init() {
+    SED_CMD=""
+    KUBEEDGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
 
-if [[ "$OSTYPE" == "darwin"* ]]
-then
-    SED_CMD=`which gsed`
```
Comment (fisherxu) [inline hack/lib/lint.sh:28]: Can just modify this line? @JooKS-me  SED_CMD=`which gsed >/dev/null 2>&1`

File: hack/lib/lint.sh (hunk 1 above)
Comment (JooKS-me) [reply hack/lib/lint.sh:29]: > I don't think this is necessary. IMHO, these two are equal :)
> 
> ```
> SED_CMD=`which gsed`
>     if [ -z $SED_CMD ]
> ```
> 
> `if ! which gsed >/dev/null 2>&1`
> 
> What is the output of `which gsed` or `make lint` cmd if gsed is not installed?

Hi, it will output this in master:
image

Comment (gy95) [reply hack/lib/lint.sh:29]: oh, i see, thanks for fixing

File: hack/lib/lint.sh (hunk 2 above)
Comment (fisherxu) [reply hack/lib/lint.sh:28]: Omit the comment, seems no needed.

File: hack/lib/lint.sh (hunk 1 above)
Comment (gy95) [reply hack/lib/lint.sh:29]: I guess it's due to `` mark
```
SED_CMD=`which sed`
    if [ -z $SED_CMD ]
```
```
SED_CMD="which sed"
    if [ -z "$SED_CMD" ]
```

Comment (JooKS-me) [reply hack/lib/lint.sh:29]: > you can try it in your linux host, modify the sed to as `sedddd`, seems needed.

I try it in my ubuntu:

image

image

Comment (gy95) [reply hack/lib/lint.sh:29]: if we want to get the result of cmd running using ``, we must ensure the cmd can be running successfully, so in the before way, the script exist unnormally when running `which sed` cmd.

**Comment by gy95** [comment]
LGTM
